// G-Swing Hole Quality Engine (Phase 3).
// ---------------------------------------
// Turns a mapped hole (auto-generated or manually enhanced) into a 0–100
// quality score plus a human-readable badge and source label. Used to
// decide whether the Premium GPS view should just play or should nudge
// the user toward the Course Mapper.
//
// Pure functions. No React, no Supabase.

import type { MappedHole } from "@/types/gswing-course-map";
import { evaluatePremiumLayers } from "@/lib/gswing-premium-readiness";
import { hasUsableHoleMapping } from "@/lib/gswing-hole-projection";

export type QualityTier =
  | "premium_ready"          // ≥ 90
  | "premium_can_enhance"    // 75–89
  | "enhancement_recommended"; // < 75

export interface QualityBadge {
  tier: QualityTier;
  label: string;
  tone: "gold" | "emerald" | "amber";
  /** True when we should surface an "Enhance Course" CTA. */
  shouldEnhance: boolean;
  /** True when we should STRONGLY recommend the mapper (blocking hint). */
  stronglyRecommend: boolean;
}

export type HoleSource = "auto" | "manual";
export type CourseSource = "auto" | "manual" | "mixed";

export interface HoleQuality {
  score: number;             // 0..100, integer
  source: HoleSource;
  badge: QualityBadge;
  usable: boolean;
}

/**
 * Detects whether the MappedHole was produced by the automatic
 * synthesizer (`gswing-auto-premium`) or hand-edited via Course Mapper.
 * The synthesizer marks the payload with `autoGenerated: true` and uses
 * an `auto:` id prefix — either is sufficient.
 */
export function detectHoleSource(hole: MappedHole | null): HoleSource {
  if (!hole) return "auto";
  const meta = hole as MappedHole & { autoGenerated?: boolean };
  if (meta.autoGenerated === true) return "auto";
  if (typeof hole.id === "string" && hole.id.startsWith("auto:")) return "auto";
  return "manual";
}

/**
 * Score a single hole 0..100.
 *   • 40 pts baseline when GPS data is usable (tee + green + pin).
 *   • Up to 60 pts distributed across premium visual layers, weighted so
 *     required layers (fairway/green/tee/boundary) count 3× optional
 *     ones (bunkers/water/trees/etc.). Layers explicitly marked "not
 *     applicable" for the hole count as satisfied.
 */
export function scoreHole(hole: MappedHole | null): number {
  if (!hole) return 0;
  const base = hasUsableHoleMapping(hole) ? 40 : 0;
  const statuses = evaluatePremiumLayers(hole);
  let earned = 0;
  let total = 0;
  for (const s of statuses) {
    const w = s.optional ? 1 : 3;
    total += w;
    if (s.satisfied) earned += w;
  }
  const layerPct = total > 0 ? earned / total : 0;
  return Math.max(0, Math.min(100, Math.round(base + layerPct * 60)));
}

export function badgeForScore(score: number): QualityBadge {
  if (score >= 90) {
    return {
      tier: "premium_ready",
      label: "Premium Ready",
      tone: "gold",
      shouldEnhance: false,
      stronglyRecommend: false,
    };
  }
  if (score >= 75) {
    return {
      tier: "premium_can_enhance",
      label: "Premium Ready · Can Enhance",
      tone: "emerald",
      shouldEnhance: true,
      stronglyRecommend: false,
    };
  }
  return {
    tier: "enhancement_recommended",
    label: "Enhancement Recommended",
    tone: "amber",
    shouldEnhance: true,
    stronglyRecommend: true,
  };
}

export function evaluateHoleQuality(hole: MappedHole | null): HoleQuality {
  const score = scoreHole(hole);
  return {
    score,
    source: detectHoleSource(hole),
    badge: badgeForScore(score),
    usable: hasUsableHoleMapping(hole),
  };
}

export interface CourseQuality {
  averageScore: number;
  holesEvaluated: number;
  holesNeedingEnhancement: number; // score < 75
  autoHoles: number;
  manualHoles: number;
  source: CourseSource;
  badge: QualityBadge;
}

export function evaluateCourseQuality(holes: Array<MappedHole | null>): CourseQuality {
  const scored = holes.map((h) => ({ h, q: evaluateHoleQuality(h) }));
  const withData = scored.filter((s) => s.q.usable);
  const avg = withData.length
    ? Math.round(withData.reduce((sum, s) => sum + s.q.score, 0) / withData.length)
    : 0;
  const autoHoles = scored.filter((s) => s.q.source === "auto" && s.q.usable).length;
  const manualHoles = scored.filter((s) => s.q.source === "manual" && s.q.usable).length;
  const source: CourseSource =
    autoHoles > 0 && manualHoles > 0 ? "mixed"
      : manualHoles > 0 ? "manual"
      : "auto";
  return {
    averageScore: avg,
    holesEvaluated: withData.length,
    holesNeedingEnhancement: withData.filter((s) => s.q.score < 75).length,
    autoHoles,
    manualHoles,
    source,
    badge: badgeForScore(avg),
  };
}

export function sourceLabel(source: HoleSource | CourseSource): string {
  switch (source) {
    case "auto": return "GolfAPI.io Auto";
    case "manual": return "Manual Enhanced";
    case "mixed": return "Mixed";
  }
}

export function badgeToneClasses(tone: QualityBadge["tone"]): string {
  switch (tone) {
    case "gold": return "border-gold/45 bg-gold/15 text-gold";
    case "emerald": return "border-emerald-500/40 bg-emerald-500/10 text-emerald-200";
    case "amber": return "border-amber-500/45 bg-amber-500/10 text-amber-200";
  }
}