// G-Swing Premium GPS — auto hole synthesizer.
// ---------------------------------------------
// Turns real GolfAPI.io geometry (tee coord + green front/center/back)
// into a fully-drawn `MappedHole` so the Premium illustrated renderer
// can show a beautiful hole immediately — no manual Course Mapper
// required. This produces the "premium visualization" layer while the
// underlying golf data (par, distances, tee positions, green shape) is
// still 100% GolfAPI.io.
//
// Auto-generated holes are marked internally (`autoGenerated=true`) so
// UI can tell the golfer "auto-generated from GolfAPI.io — map for a
// finer illustration". They are NEVER persisted to Supabase.

import type { LatLng } from "@/lib/gps-utils";
import type { GreenData, HoleGpsResponse, TeeBox } from "@/lib/golf-gps-api";
import type {
  HazardGeometry,
  MappedHole,
  TeeBoxMarker,
} from "@/types/gswing-course-map";

const EARTH_R = 6371000;
const YARDS_PER_M = 1.09361;

function toRad(d: number): number { return (d * Math.PI) / 180; }
function toDeg(r: number): number { return (r * 180) / Math.PI; }

/** Destination point given start, bearing (deg from N), distance (m). */
function destination(start: LatLng, bearingDeg: number, distanceM: number): LatLng {
  const br = toRad(bearingDeg);
  const d = distanceM / EARTH_R;
  const lat1 = toRad(start.lat);
  const lng1 = toRad(start.lng);
  const lat2 = Math.asin(
    Math.sin(lat1) * Math.cos(d) + Math.cos(lat1) * Math.sin(d) * Math.cos(br),
  );
  const lng2 = lng1 + Math.atan2(
    Math.sin(br) * Math.sin(d) * Math.cos(lat1),
    Math.cos(d) - Math.sin(lat1) * Math.sin(lat2),
  );
  return { lat: toDeg(lat2), lng: ((toDeg(lng2) + 540) % 360) - 180 };
}

function bearing(a: LatLng, b: LatLng): number {
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const dLng = toRad(b.lng - a.lng);
  const y = Math.sin(dLng) * Math.cos(lat2);
  const x = Math.cos(lat1) * Math.sin(lat2) - Math.sin(lat1) * Math.cos(lat2) * Math.cos(dLng);
  return (toDeg(Math.atan2(y, x)) + 360) % 360;
}

function meters(a: LatLng, b: LatLng): number {
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const h = Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * EARTH_R * Math.asin(Math.sqrt(h));
}

/** [lng, lat] tuple used by Mapbox / our polygon rings. */
function toRing(pt: LatLng): [number, number] { return [pt.lng, pt.lat]; }

/**
 * Rectangle corridor along a centreline (start → end) with a half-width
 * (metres) on each side. Returns a closed ring.
 */
function corridorPolygon(
  start: LatLng,
  end: LatLng,
  halfWidthM: number,
  overshootStartM = 0,
  overshootEndM = 0,
): Array<[number, number]> {
  const b = bearing(start, end);
  const left = (b + 270) % 360;
  const right = (b + 90) % 360;
  const back = (b + 180) % 360;
  const s = overshootStartM > 0 ? destination(start, back, overshootStartM) : start;
  const e = overshootEndM > 0 ? destination(end, b, overshootEndM) : end;
  return [
    toRing(destination(s, left, halfWidthM)),
    toRing(destination(e, left, halfWidthM)),
    toRing(destination(e, right, halfWidthM)),
    toRing(destination(s, right, halfWidthM)),
    toRing(destination(s, left, halfWidthM)),
  ];
}

/**
 * Ellipse polygon around `center`, semi-major/minor in metres, oriented
 * so the major axis follows `orientationDeg` (bearing from N).
 */
function ellipsePolygon(
  center: LatLng,
  semiMajorM: number,
  semiMinorM: number,
  orientationDeg: number,
  segments = 28,
): Array<[number, number]> {
  const pts: Array<[number, number]> = [];
  for (let i = 0; i < segments; i++) {
    const t = (i / segments) * 2 * Math.PI;
    // Parametric ellipse in local frame (x=along major, y=perp).
    const x = semiMajorM * Math.cos(t);
    const y = semiMinorM * Math.sin(t);
    // Convert local (x,y) to distance+bearing offset from the axis.
    const dist = Math.sqrt(x * x + y * y);
    const localAngle = toDeg(Math.atan2(y, x)); // 0 = along major
    const brg = (orientationDeg + localAngle + 360) % 360;
    pts.push(toRing(destination(center, brg, dist)));
  }
  pts.push(pts[0]);
  return pts;
}

function circlePolygon(center: LatLng, radiusM: number, segments = 20): Array<[number, number]> {
  return ellipsePolygon(center, radiusM, radiusM, 0, segments);
}

function pickBestTee(tees: TeeBox[]): TeeBox | null {
  if (!tees.length) return null;
  // Prefer white/regular, then any tee with coords.
  const priority = ["white", "regular", "men", "blue", "yellow"];
  for (const p of priority) {
    const hit = tees.find((t) => (t.color ?? t.name ?? "").toLowerCase().includes(p));
    if (hit && Number.isFinite(hit.lat) && Number.isFinite(hit.lng)) return hit;
  }
  return tees.find((t) => Number.isFinite(t.lat) && Number.isFinite(t.lng)) ?? null;
}

/**
 * Build a fully-drawn Premium `MappedHole` purely from live GolfAPI.io
 * data. Returns null when the essential coordinates (a tee AND a green
 * center) aren't available — the caller should fall back to the missing
 * mapping UI.
 */
export function synthesizePremiumHole(
  gps: HoleGpsResponse | null,
  holeNumber: number,
): (MappedHole & { autoGenerated: true }) | null {
  if (!gps) return null;
  const bestTee = pickBestTee(gps.tee_boxes ?? []);
  const green: GreenData | null = gps.green;
  if (!bestTee || !green?.center) return null;

  const tee: LatLng = { lat: bestTee.lat, lng: bestTee.lng };
  const centerG: LatLng = green.center;
  const frontG: LatLng | null = green.front ?? null;
  const backG: LatLng | null = green.back ?? null;
  const pin: LatLng | null = green.pin ?? null;

  const teeToGreenBearing = bearing(tee, centerG);
  const holeLengthM = meters(tee, centerG);

  // ---- Green polygon ---------------------------------------------------
  // Prefer real depth/width from GolfAPI; fall back to sensible defaults.
  const depthM = green.depth_yards && green.depth_yards > 0
    ? green.depth_yards / YARDS_PER_M
    : (frontG && backG ? Math.max(12, meters(frontG, backG)) : 22);
  const widthM = green.width_yards && green.width_yards > 0
    ? green.width_yards / YARDS_PER_M
    : Math.max(depthM * 0.85, 18);
  const greenPolygon = ellipsePolygon(
    centerG,
    depthM / 2,
    widthM / 2,
    teeToGreenBearing,
  );

  // ---- Fairway corridor ------------------------------------------------
  // Width scales gently with hole length. Stops short of the green so
  // the green shape is visually distinct.
  const halfW = Math.min(28, Math.max(14, holeLengthM * 0.04));
  const cutoff = destination(centerG, (teeToGreenBearing + 180) % 360, depthM * 0.55 + 6);
  const fairwayPolygon = corridorPolygon(tee, cutoff, halfW, 0, 0);

  // ---- Tee polygon (small rectangle around the tee marker) -------------
  const teePolygon = corridorPolygon(
    destination(tee, (teeToGreenBearing + 180) % 360, 4),
    destination(tee, teeToGreenBearing, 6),
    5,
  );

  // ---- Hole boundary (generous rough buffer around the corridor) -------
  const boundaryHalf = halfW + Math.max(20, holeLengthM * 0.05);
  const holeBoundary = corridorPolygon(tee, centerG, boundaryHalf, 12, depthM);

  // ---- Hazards from GolfAPI (only the ones with real coords) -----------
  const hazards: HazardGeometry[] = [];
  for (const h of gps.hazards ?? []) {
    if (h.lat == null || h.lng == null) continue;
    if (h.type === "dogleg" || h.type === "layup") continue;
    const c: LatLng = { lat: h.lat, lng: h.lng };
    // Estimate radius by hazard type — bunkers small, water bigger.
    const rM = h.type === "water" ? 22 : h.type === "trees" ? 26 : 10;
    const poly = circlePolygon(c, rM);
    hazards.push({
      id: `auto-${holeNumber}-${hazards.length}`,
      name: h.label ?? h.type,
      type: h.type === "water"
        ? "water"
        : h.type === "trees"
          ? "trees"
          : h.type === "ob"
            ? "out_of_bounds"
            : "bunker",
      side: null,
      polygon: poly,
      front: null,
      carry: null,
      center: c,
      notes: null,
    });
  }

  const tees: TeeBoxMarker[] = (gps.tee_boxes ?? [])
    .filter((t) => Number.isFinite(t.lat) && Number.isFinite(t.lng))
    .map((t, idx) => ({
      id: `auto-tee-${holeNumber}-${idx}`,
      name: t.name ?? t.color ?? "Tee",
      coordinate: { lat: t.lat, lng: t.lng },
      yardage: null,
    }));
  if (tees.length === 0) {
    tees.push({ id: `auto-tee-${holeNumber}`, name: "Tee", coordinate: tee, yardage: null });
  }

  // Mark all optional premium visual layers we didn't synthesise as N/A
  // so `isPremiumReady` treats the hole as ready to render without
  // demanding trees/waste/OB/rough polygons the API never provides.
  const naLayers = ["rough_polygon", "waste", "ob", "cart_path"];
  if (!hazards.some((h) => h.type === "trees")) naLayers.push("trees");
  if (!hazards.some((h) => h.type === "water" || h.type === "penalty_area")) naLayers.push("water");
  if (!hazards.some((h) => h.type === "bunker")) naLayers.push("bunkers");

  return {
    id: `auto:${gps.course_id}:${holeNumber}`,
    holeNumber,
    par: gps.par ?? null,
    lengthYards: holeLengthM > 0 ? Math.round(holeLengthM * YARDS_PER_M) : null,
    lengthMeters: holeLengthM > 0 ? Math.round(holeLengthM) : null,
    tees,
    green: {
      front: frontG,
      center: centerG,
      back: backG,
      polygon: greenPolygon,
      slopeNote: null,
    },
    pin: pin ? { coordinate: pin, setOn: null, notes: null } : null,
    hazards,
    layups: [],
    doglegs: [],
    landingZones: [],
    fairwayPolygon,
    teePolygon,
    holeBoundary,
    roughPolygon: null,
    cartPath: null,
    naLayers,
    autoGenerated: true,
  };
}
