// G-Swing Premium GPS — auto hole synthesizer.
// ---------------------------------------------
// Turns real GolfAPI.io geometry (tee coord + green front/center/back)
// into a fully-drawn `MappedHole` so the Premium illustrated renderer
// can show a beautiful hole immediately — no manual Course Mapper
// required. This produces the "premium visualization" layer while the
// underlying golf data (par, distances, tee positions, green shape) is
// still 100% GolfAPI.io.
//
// Auto-generated holes are marked internally (`autoGenerated=true`) so
// UI can tell the golfer "auto-generated from GolfAPI.io — map for a
// finer illustration". They are NEVER persisted to Supabase.

import type { LatLng } from "@/lib/gps-utils";
import type {
  GeoJsonLineString,
  GeoJsonPolygon,
  GreenData,
  Hazard,
  HoleGpsResponse,
  TeeBox,
} from "@/lib/golf-gps-api";
import type {
  HazardGeometry,
  MappedHole,
  TeeBoxMarker,
} from "@/types/gswing-course-map";

const EARTH_R = 6371000;
const YARDS_PER_M = 1.09361;

function toRad(d: number): number { return (d * Math.PI) / 180; }
function toDeg(r: number): number { return (r * 180) / Math.PI; }

/** Destination point given start, bearing (deg from N), distance (m). */
function destination(start: LatLng, bearingDeg: number, distanceM: number): LatLng {
  const br = toRad(bearingDeg);
  const d = distanceM / EARTH_R;
  const lat1 = toRad(start.lat);
  const lng1 = toRad(start.lng);
  const lat2 = Math.asin(
    Math.sin(lat1) * Math.cos(d) + Math.cos(lat1) * Math.sin(d) * Math.cos(br),
  );
  const lng2 = lng1 + Math.atan2(
    Math.sin(br) * Math.sin(d) * Math.cos(lat1),
    Math.cos(d) - Math.sin(lat1) * Math.sin(lat2),
  );
  return { lat: toDeg(lat2), lng: ((toDeg(lng2) + 540) % 360) - 180 };
}

function bearing(a: LatLng, b: LatLng): number {
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const dLng = toRad(b.lng - a.lng);
  const y = Math.sin(dLng) * Math.cos(lat2);
  const x = Math.cos(lat1) * Math.sin(lat2) - Math.sin(lat1) * Math.cos(lat2) * Math.cos(dLng);
  return (toDeg(Math.atan2(y, x)) + 360) % 360;
}

function meters(a: LatLng, b: LatLng): number {
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const h = Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * EARTH_R * Math.asin(Math.sqrt(h));
}

/** [lng, lat] tuple used by Mapbox / our polygon rings. */
function toRing(pt: LatLng): [number, number] { return [pt.lng, pt.lat]; }

// ── Deterministic PRNG (mulberry32) ────────────────────────────────────
function hashSeed(s: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function makeRng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ── Convert GeoJSON polygon coords → outer ring [lng, lat][] ───────────
function geoJsonPolygonToRing(
  poly: GeoJsonPolygon | GeoJsonLineString | null | undefined,
): Array<[number, number]> | null {
  if (!poly) return null;
  if (poly.type === "Polygon") {
    const outer = poly.coordinates?.[0];
    if (!outer || outer.length < 3) return null;
    const ring = outer.map(([lng, lat]) => [lng, lat] as [number, number]);
    if (
      ring[0][0] !== ring[ring.length - 1][0] ||
      ring[0][1] !== ring[ring.length - 1][1]
    ) ring.push(ring[0]);
    return ring;
  }
  return null;
}

// ── Catmull-Rom smoothing + resampling of a centerline ─────────────────
function catmullRom(p0: LatLng, p1: LatLng, p2: LatLng, p3: LatLng, t: number): LatLng {
  const t2 = t * t;
  const t3 = t2 * t;
  const lat = 0.5 * (
    2 * p1.lat +
    (-p0.lat + p2.lat) * t +
    (2 * p0.lat - 5 * p1.lat + 4 * p2.lat - p3.lat) * t2 +
    (-p0.lat + 3 * p1.lat - 3 * p2.lat + p3.lat) * t3
  );
  const lng = 0.5 * (
    2 * p1.lng +
    (-p0.lng + p2.lng) * t +
    (2 * p0.lng - 5 * p1.lng + 4 * p2.lng - p3.lng) * t2 +
    (-p0.lng + 3 * p1.lng - 3 * p2.lng + p3.lng) * t3
  );
  return { lat, lng };
}
function smoothCenterline(controls: LatLng[], samples = 24): LatLng[] {
  if (controls.length < 2) return controls.slice();
  if (controls.length === 2) {
    const out: LatLng[] = [];
    for (let i = 0; i <= samples; i++) {
      const t = i / samples;
      out.push({
        lat: controls[0].lat + (controls[1].lat - controls[0].lat) * t,
        lng: controls[0].lng + (controls[1].lng - controls[0].lng) * t,
      });
    }
    return out;
  }
  const pts = [controls[0], ...controls, controls[controls.length - 1]];
  const out: LatLng[] = [];
  const segCount = pts.length - 3;
  const perSeg = Math.max(2, Math.round(samples / segCount));
  for (let i = 0; i < segCount; i++) {
    for (let j = 0; j < perSeg; j++) {
      out.push(catmullRom(pts[i], pts[i + 1], pts[i + 2], pts[i + 3], j / perSeg));
    }
  }
  out.push(controls[controls.length - 1]);
  return out;
}

function centerlineBearingAt(line: LatLng[], i: number): number {
  const a = line[Math.max(0, i - 1)];
  const b = line[Math.min(line.length - 1, i + 1)];
  return bearing(a, b);
}

/** Build an organic variable-width polygon around a centerline. */
function organicBufferPolygon(
  line: LatLng[],
  widthAt: (t: number) => number,
  rand: () => number,
  noiseFrac: number,
): Array<[number, number]> {
  const n = line.length;
  if (n < 2) return [];
  const left: Array<[number, number]> = [];
  const right: Array<[number, number]> = [];
  // Low-frequency noise via pre-baked control values, interpolated.
  const controlCount = Math.max(4, Math.round(n / 4));
  const noiseL: number[] = Array.from({ length: controlCount }, () => (rand() * 2 - 1) * noiseFrac);
  const noiseR: number[] = Array.from({ length: controlCount }, () => (rand() * 2 - 1) * noiseFrac);
  const sampleNoise = (arr: number[], t: number): number => {
    const x = t * (arr.length - 1);
    const i = Math.floor(x);
    const f = x - i;
    const a = arr[i];
    const b = arr[Math.min(arr.length - 1, i + 1)];
    return a + (b - a) * f;
  };
  for (let i = 0; i < n; i++) {
    const t = i / (n - 1);
    const brg = centerlineBearingAt(line, i);
    const w = widthAt(t);
    const wl = Math.max(2, w * (1 + sampleNoise(noiseL, t)));
    const wr = Math.max(2, w * (1 + sampleNoise(noiseR, t)));
    left.push(toRing(destination(line[i], (brg + 270) % 360, wl)));
    right.push(toRing(destination(line[i], (brg + 90) % 360, wr)));
  }
  const ring = [...left, ...right.reverse(), left[0]];
  return ring;
}

/** Organic blob polygon around a point. */
function organicBlob(
  center: LatLng,
  baseRadiusM: number,
  rand: () => number,
  vertices = 14,
): Array<[number, number]> {
  const pts: Array<[number, number]> = [];
  for (let i = 0; i < vertices; i++) {
    const ang = (i / vertices) * 360;
    const r = baseRadiusM * (0.75 + rand() * 0.5);
    pts.push(toRing(destination(center, ang, r)));
  }
  pts.push(pts[0]);
  return pts;
}

/** Project a point onto the nearest centerline segment; return
 *  { index, param, projected, side (+1 left / -1 right) }. */
function projectOntoCenterline(
  line: LatLng[],
  p: LatLng,
): { index: number; projected: LatLng; side: 1 | -1; bearingDeg: number } {
  // Cheap: pick nearest sample, then decide side using cross product.
  let bestI = 0;
  let bestD = Infinity;
  for (let i = 0; i < line.length; i++) {
    const d = meters(line[i], p);
    if (d < bestD) { bestD = d; bestI = i; }
  }
  const brg = centerlineBearingAt(line, bestI);
  // Bearing from line point to p; side by signed angle diff.
  const brgToP = bearing(line[bestI], p);
  let diff = ((brgToP - brg + 540) % 360) - 180; // -180..180
  const side: 1 | -1 = diff >= 0 ? -1 : 1; // right of travel = +90 => diff positive
  return { index: bestI, projected: line[bestI], side, bearingDeg: brg };
}

/**
 * Rectangle corridor along a centreline (start → end) with a half-width
 * (metres) on each side. Returns a closed ring.
 */
function corridorPolygon(
  start: LatLng,
  end: LatLng,
  halfWidthM: number,
  overshootStartM = 0,
  overshootEndM = 0,
): Array<[number, number]> {
  const b = bearing(start, end);
  const left = (b + 270) % 360;
  const right = (b + 90) % 360;
  const back = (b + 180) % 360;
  const s = overshootStartM > 0 ? destination(start, back, overshootStartM) : start;
  const e = overshootEndM > 0 ? destination(end, b, overshootEndM) : end;
  return [
    toRing(destination(s, left, halfWidthM)),
    toRing(destination(e, left, halfWidthM)),
    toRing(destination(e, right, halfWidthM)),
    toRing(destination(s, right, halfWidthM)),
    toRing(destination(s, left, halfWidthM)),
  ];
}

/**
 * Ellipse polygon around `center`, semi-major/minor in metres, oriented
 * so the major axis follows `orientationDeg` (bearing from N).
 */
function ellipsePolygon(
  center: LatLng,
  semiMajorM: number,
  semiMinorM: number,
  orientationDeg: number,
  segments = 28,
): Array<[number, number]> {
  const pts: Array<[number, number]> = [];
  for (let i = 0; i < segments; i++) {
    const t = (i / segments) * 2 * Math.PI;
    // Parametric ellipse in local frame (x=along major, y=perp).
    const x = semiMajorM * Math.cos(t);
    const y = semiMinorM * Math.sin(t);
    // Convert local (x,y) to distance+bearing offset from the axis.
    const dist = Math.sqrt(x * x + y * y);
    const localAngle = toDeg(Math.atan2(y, x)); // 0 = along major
    const brg = (orientationDeg + localAngle + 360) % 360;
    pts.push(toRing(destination(center, brg, dist)));
  }
  pts.push(pts[0]);
  return pts;
}

function pickBestTee(tees: TeeBox[]): TeeBox | null {
  if (!tees.length) return null;
  // Prefer white/regular, then any tee with coords.
  const priority = ["white", "regular", "men", "blue", "yellow"];
  for (const p of priority) {
    const hit = tees.find((t) => (t.color ?? "").toLowerCase().includes(p));
    if (hit && Number.isFinite(hit.lat) && Number.isFinite(hit.lng)) return hit;
  }
  return tees.find((t) => Number.isFinite(t.lat) && Number.isFinite(t.lng)) ?? null;
}

/**
 * Build a fully-drawn Premium `MappedHole` purely from live GolfAPI.io
 * data. Returns null when the essential coordinates (a tee AND a green
 * center) aren't available — the caller should fall back to the missing
 * mapping UI.
 */
export function synthesizePremiumHole(
  gps: HoleGpsResponse | null,
  holeNumber: number,
): (MappedHole & { autoGenerated: true }) | null {
  if (!gps) return null;
  const bestTee = pickBestTee(gps.tee_boxes ?? []);
  const green: GreenData | null = gps.green;
  if (!bestTee || !green?.center) return null;

  const tee: LatLng = { lat: bestTee.lat, lng: bestTee.lng };
  const centerG: LatLng = green.center;
  const frontG: LatLng | null = green.front ?? null;
  const backG: LatLng | null = green.back ?? null;
  const pin: LatLng | null = green.pin ?? null;

  const teeToGreenBearing = bearing(tee, centerG);
  const holeLengthM = meters(tee, centerG);

  // ---- Green polygon ---------------------------------------------------
  // Prefer real depth/width from GolfAPI; fall back to sensible defaults.
  const depthM = green.depth_yards && green.depth_yards > 0
    ? green.depth_yards / YARDS_PER_M
    : (frontG && backG ? Math.max(12, meters(frontG, backG)) : 22);
  const widthM = green.width_yards && green.width_yards > 0
    ? green.width_yards / YARDS_PER_M
    : Math.max(depthM * 0.85, 18);
  const greenPolygon = ellipsePolygon(
    centerG,
    depthM / 2,
    widthM / 2,
    teeToGreenBearing,
  );

  // ---- Fairway corridor ------------------------------------------------
  // Width scales gently with hole length. Stops short of the green so
  // the green shape is visually distinct.
  const halfW = Math.min(28, Math.max(14, holeLengthM * 0.04));
  const cutoff = destination(centerG, (teeToGreenBearing + 180) % 360, depthM * 0.55 + 6);
  const fairwayPolygon = corridorPolygon(tee, cutoff, halfW, 0, 0);

  // ---- Tee polygon (small rectangle around the tee marker) -------------
  const teePolygon = corridorPolygon(
    destination(tee, (teeToGreenBearing + 180) % 360, 4),
    destination(tee, teeToGreenBearing, 6),
    5,
  );

  // ---- Hole boundary (generous rough buffer around the corridor) -------
  const boundaryHalf = halfW + Math.max(20, holeLengthM * 0.05);
  const holeBoundary = corridorPolygon(tee, centerG, boundaryHalf, 12, depthM);

  // ---- Hazards from GolfAPI (only the ones with real coords) -----------
  const hazards: HazardGeometry[] = [];
  for (const h of gps.hazards ?? []) {
    if (h.lat == null || h.lng == null) continue;
    if (h.type === "dogleg" || h.type === "layup") continue;
    const c: LatLng = { lat: h.lat, lng: h.lng };
    // Estimate radius by hazard type — bunkers small, water bigger.
    const rM = h.type === "water" ? 22 : h.type === "trees" ? 26 : 10;
    const poly = circlePolygon(c, rM);
    hazards.push({
      id: `auto-${holeNumber}-${hazards.length}`,
      name: h.label ?? h.type,
      type: h.type === "water"
        ? "water"
        : h.type === "trees"
          ? "trees"
          : h.type === "ob"
            ? "out_of_bounds"
            : "bunker",
      side: null,
      polygon: poly,
      front: null,
      carry: null,
      center: c,
      notes: null,
    });
  }

  const tees: TeeBoxMarker[] = (gps.tee_boxes ?? [])
    .filter((t) => Number.isFinite(t.lat) && Number.isFinite(t.lng))
    .map((t, idx) => ({
      id: `auto-tee-${holeNumber}-${idx}`,
      name: t.color ?? "Tee",
      coordinate: { lat: t.lat, lng: t.lng },
      yardage: t.yardage ?? null,
    }));
  if (tees.length === 0) {
    tees.push({ id: `auto-tee-${holeNumber}`, name: "Tee", coordinate: tee, yardage: null });
  }

  // Mark all optional premium visual layers we didn't synthesise as N/A
  // so `isPremiumReady` treats the hole as ready to render without
  // demanding trees/waste/OB/rough polygons the API never provides.
  const naLayers = ["rough_polygon", "waste", "ob", "cart_path"];
  if (!hazards.some((h) => h.type === "trees")) naLayers.push("trees");
  if (!hazards.some((h) => h.type === "water" || h.type === "penalty_area")) naLayers.push("water");
  if (!hazards.some((h) => h.type === "bunker")) naLayers.push("bunkers");

  return {
    id: `auto:${gps.course_id}:${holeNumber}`,
    holeNumber,
    par: gps.par ?? null,
    lengthYards: holeLengthM > 0 ? Math.round(holeLengthM * YARDS_PER_M) : null,
    lengthMeters: holeLengthM > 0 ? Math.round(holeLengthM) : null,
    tees,
    green: {
      front: frontG,
      center: centerG,
      back: backG,
      polygon: greenPolygon,
      slopeNote: null,
    },
    pin: pin ? { coordinate: pin, setOn: null, notes: null } : null,
    hazards,
    layups: [],
    doglegs: [],
    landingZones: [],
    fairwayPolygon,
    teePolygon,
    holeBoundary,
    roughPolygon: null,
    cartPath: null,
    naLayers,
    autoGenerated: true,
  };
}
