// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";
import { auth } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { z } from "npm:zod@^4.4.3";
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List golf courses",
  description: "List golf courses indexed by G-Swing. Optional country filter and free-text name search. Returns id, name, country, city, holes_count, latitude, longitude.",
  inputSchema: {
    country: z.string().trim().min(2).max(64).nullable().describe("ISO country name or code to filter by (e.g. 'United Arab Emirates')."),
    search: z.string().trim().min(1).max(120).nullable().describe("Case-insensitive substring match against course name."),
    limit: z.number().int().min(1).max(200).nullable().describe("Max rows to return (default 50, cap 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ country, search, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("golf_courses").select("id,name,country,city,holes_count,lat,lng").order("country").order("name").limit(Math.min(limit ?? 50, 200));
    if (country) q = q.ilike("country", `%${country}%`);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? `Found ${rows.length} course(s):
${rows.map(
            (c) => `- ${c.name} \u2014 ${c.city ?? "?"}, ${c.country ?? "?"} (${c.holes_count ?? "?"} holes) [id: ${c.id}]`
          ).join("\n")}` : "No courses matched."
        }
      ],
      structuredContent: { courses: rows }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_course_default = defineTool2({
  name: "get_course",
  title: "Get course details",
  description: "Get full detail for a single course, including its holes (number, par, yardage).",
  inputSchema: {
    course_id: z2.string().uuid().describe("The course id returned by list_courses.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data: course, error } = await supabase.from("golf_courses").select("*").eq("id", course_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!course) {
      return { content: [{ type: "text", text: "Course not found." }], isError: true };
    }
    const { data: holes } = await supabase.from("course_holes").select("hole_number,par,yardage").eq("course_id", course_id).order("hole_number");
    const holesRows = holes ?? [];
    return {
      content: [
        {
          type: "text",
          text: `${course.name} \u2014 ${course.city ?? "?"}, ${course.country ?? "?"}
Holes: ${holesRows.length}
${holesRows.map(
            (h) => `  H${h.hole_number}  Par ${h.par ?? "?"}  ${h.yardage ?? "?"}y`
          ).join("\n")}`
        }
      ],
      structuredContent: { course, holes: holesRows }
    };
  }
});

// src/lib/mcp/tools/get-hole-gps.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z3 } from "npm:zod@^4.4.3";
function haversineYards(lat1, lon1, lat2, lon2) {
  const R = 6371e3;
  const toRad = (x) => x * Math.PI / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * R * Math.asin(Math.sqrt(a)) * 1.09361);
}
var get_hole_gps_default = defineTool3({
  name: "get_hole_gps",
  title: "Get hole GPS data",
  description: "Get GPS geometry for one hole: tee boxes, green front/center/back, and hazards. If lat/lng are provided, distances from that point are included.",
  inputSchema: {
    course_id: z3.string().uuid().describe("Course id from list_courses."),
    hole_number: z3.number().int().min(1).max(36).describe("Hole number, 1-based."),
    lat: z3.number().nullable().describe("Optional player latitude for distance calculations."),
    lng: z3.number().nullable().describe("Optional player longitude for distance calculations."),
    unit: z3.enum(["yards", "meters"]).nullable().describe("Distance unit for computed player distances (default yards).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id, hole_number, lat, lng, unit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data: hole, error: hErr } = await supabase.from("course_holes").select("id,hole_number,par,yardage").eq("course_id", course_id).eq("hole_number", hole_number).maybeSingle();
    if (hErr) {
      return { content: [{ type: "text", text: `Error: ${hErr.message}` }], isError: true };
    }
    if (!hole) {
      return { content: [{ type: "text", text: "Hole not found." }], isError: true };
    }
    const [teesRes, greenRes, hazRes] = await Promise.all([
      supabase.from("tee_boxes").select("*").eq("hole_id", hole.id).order("color"),
      supabase.from("greens").select("*").eq("hole_id", hole.id).maybeSingle(),
      supabase.from("hazards").select("*").eq("hole_id", hole.id).order("type")
    ]);
    const tees = teesRes.data ?? [];
    const green = greenRes.data ?? null;
    const hazards = hazRes.data ?? [];
    const useMeters = unit === "meters";
    const distYd = (a) => a && lat != null && lng != null ? haversineYards(lat, lng, a.lat, a.lng) : null;
    const conv = (y) => y == null ? null : useMeters ? Math.round(y * 0.9144) : y;
    const playerDist = lat != null && lng != null && green ? {
      to_green_front: conv(distYd({ lat: green.front_lat, lng: green.front_lng })),
      to_green_center: conv(distYd({ lat: green.center_lat, lng: green.center_lng })),
      to_green_back: conv(distYd({ lat: green.back_lat, lng: green.back_lng })),
      unit: useMeters ? "m" : "y"
    } : null;
    return {
      content: [
        {
          type: "text",
          text: `Hole ${hole.hole_number} \u2014 Par ${hole.par ?? "?"}, ${hole.yardage ?? "?"}y
Tees: ${tees.length}, Hazards: ${hazards.length}${playerDist ? `
From player: F ${playerDist.to_green_front ?? "?"} / C ${playerDist.to_green_center ?? "?"} / B ${playerDist.to_green_back ?? "?"} ${playerDist.unit}` : ""}`
        }
      ],
      structuredContent: { hole, tees, green, hazards, player_distances: playerDist }
    };
  }
});

// src/lib/mcp/index.ts
var supabaseUrl = (typeof process !== "undefined" ? process.env.SUPABASE_URL : void 0) ?? (typeof process !== "undefined" ? process.env.VITE_SUPABASE_URL : void 0) ?? "";
var mcp_default = defineMcp({
  name: "g-swing-mcp",
  title: "G-Swing MCP",
  version: "0.1.0",
  instructions: "Tools for the G-Swing golf app. Use `list_courses` to discover courses, `get_course` for full detail and hole list, and `get_hole_gps` for per-hole tee/green/hazard geometry (optionally with player distances when lat/lng are supplied).",
  auth: auth.oauth.issuer({
    issuer: `${supabaseUrl.replace(/\/$/, "")}/auth/v1`,
    acceptedAudiences: ["authenticated"],
    resourceName: "G-Swing MCP"
  }),
  tools: [list_courses_default, get_course_default, get_hole_gps_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
