import { useEffect, useMemo, useRef, useState } from "react";
import type { LatLng } from "@/lib/gps-utils";
import type { HazardGeometry, MappedHole } from "@/types/gswing-course-map";
import {
  buildHoleBounds,
  calculateFeatureCentroid,
  calculateMeasurementFromTap,
  fitHoleToViewport,
  hasUsableHoleMapping,
  projectLatLngToHoleCanvas,
  unprojectHoleCanvasToLatLng,
  type FittedProjection,
} from "@/lib/gswing-hole-projection";
import {
  evaluatePremiumLayers,
  isPremiumReady,
  missingPremiumLayers,
  premiumProgress,
} from "@/lib/gswing-premium-readiness";
import {
  badgeToneClasses,
  evaluateHoleQuality,
  sourceLabel,
} from "@/lib/gswing-hole-quality";
import { fromMappedHole } from "@/lib/rendering/course-geometry-model";
import { getRenderableGeometrySource } from "@/lib/rendering/course-renderability";
import { computePremiumBounds } from "@/lib/rendering/premium-framing";
import { PREMIUM_LAYER_ORDER } from "@/lib/rendering/premium-layers";

type PremiumGeometrySource = "none" | "mapped-polygons" | "auto-osm-polygons" | "auto-generated-fallback";

/**
 * G-Swing Premium Hole Renderer
 * ------------------------------
 * Polygon-driven illustrated aerial view. The renderer ONLY draws a
 * premium illustration when the hole is Premium Ready (every required
 * visual layer is either drawn or explicitly marked Not Applicable).
 * Otherwise a "Premium Mapping Required" gate is shown — never the old
 * glowing vector corridor.
 *
 * Tap-to-measure: a tap on the SVG is unprojected back into real lat/lng
 * and emitted to the parent so the bottom sheet shows a real haversine
 * distance from the live player GPS.
 */
export interface PremiumHoleRendererProps {
  mappedHole: MappedHole | null;
  playerPosition: LatLng | null;
  gpsAccuracy: number | null;
  selectedHoleNumber: number;
  unit: "yards" | "meters";
  isMeasuring: boolean;
  measurementTarget: LatLng | null;
  onMapTap: (latlng: LatLng) => void;
  onClearMeasurement?: () => void;
  /**
   * Owner-only enhancement: when true, the Premium Mapping Required gate
   * surfaces "Open Course Mapper" + "Mark layer not applicable" actions.
   * Hidden completely for non-owner users.
   */
  isOwner?: boolean;
  onOpenMapper?: () => void;
  onMarkLayerNa?: (layerKey: string) => void | Promise<void>;
  /**
   * Optional: when provided, the Premium Mapping Required gate shows a
   * "Continue with Satellite Only" button that toggles the parent's
   * map view. Wired by GpsMap so every user (not just owners) can fall
   * back to the satellite renderer with one tap.
   */
  onContinueSatellite?: () => void;
}

const PADDING = 44;

// ─── Per-par viewport padding multipliers ────────────────────────────────────
// Par 3: tighter zoom so the compact hole fills the frame. Par 5: pull back so
// the full corridor is visible. Par 4: default. Applies to paddingPx only;
// paddingBottomPx is unchanged (reserved for the bottom sheet).
function parPaddingPx(par: number | null): number {
  if (par === 3) return 22;   // zoom in — green becomes focal point
  if (par === 5) return 62;   // zoom out — whole corridor visible
  return PADDING;             // par 4 / unknown
}

function classifyGeometrySource(hole: MappedHole | null): PremiumGeometrySource {
  if (!hole) return "none";
  const autoGenerated = Boolean((hole as MappedHole & { autoGenerated?: boolean }).autoGenerated);
  const hasFeaturePolygons = Boolean(
    hole.fairwayPolygon ||
      hole.teePolygon ||
      hole.green.polygon ||
      hole.hazards.some((h) => h.polygon),
  );
  const hasCoursePolygons = Boolean(
    hole.holeBoundary || hole.roughPolygon || hole.cartPath || hasFeaturePolygons,
  );
  if (!autoGenerated && hasFeaturePolygons) return "mapped-polygons";
  if (autoGenerated && hasCoursePolygons) return "auto-osm-polygons";
  if (autoGenerated) return "auto-generated-fallback";
  return "none";
}

function polygonPointCount(ring: Array<[number, number]> | null | undefined): number {
  return ring?.length ?? 0;
}

// ─── Per-hole ambient personality ────────────────────────────────────────────
// Returns a subtle tint overlay that gives each hole a unique atmospheric feel
// without touching geometry. Values are CSS rgba strings and opacities.
function holePersonality(holeNum: number): {
  tint: string;        // radial gradient overlay colour
  tintOpacity: number;
  lightAngle: number;  // sunlight azimuth in degrees (affects mow stripe highlight)
  ambientTag: string;  // short descriptor for debug
} {
  const personalities: Record<number, { tint: string; tintOpacity: number; lightAngle: number; ambientTag: string }> = {
    1: { tint: "#1a3a8c", tintOpacity: 0.06, lightAngle: 135, ambientTag: "lakeside-dawn" },
    2: { tint: "#0d2e12", tintOpacity: 0.05, lightAngle: 110, ambientTag: "tree-lined" },
    3: { tint: "#103070", tintOpacity: 0.07, lightAngle: 150, ambientTag: "par3-dramatic" },
    4: { tint: "#f5c84b", tintOpacity: 0.03, lightAngle:  90, ambientTag: "championship-noon" },
    5: { tint: "#1a5c9c", tintOpacity: 0.08, lightAngle: 125, ambientTag: "water-carry" },
    6: { tint: "#0a2c0a", tintOpacity: 0.04, lightAngle: 100, ambientTag: "long-par5" },
    7: { tint: "#1e3a1e", tintOpacity: 0.05, lightAngle: 155, ambientTag: "dogleg-afternoon" },
    8: { tint: "#103070", tintOpacity: 0.06, lightAngle: 145, ambientTag: "par3-dusk" },
    9: { tint: "#2a1a0a", tintOpacity: 0.05, lightAngle: 120, ambientTag: "finishing-hole" },
  };
  return personalities[holeNum] ?? { tint: "#0d2e12", tintOpacity: 0.04, lightAngle: 120, ambientTag: "default" };
}

export function PremiumHoleRenderer({
  mappedHole,
  playerPosition,
  gpsAccuracy,
  selectedHoleNumber,
  unit,
  isMeasuring,
  measurementTarget,
  onMapTap,
  isOwner,
  onOpenMapper,
  onMarkLayerNa,
  onContinueSatellite,
}: PremiumHoleRendererProps) {
  const wrapRef = useRef<HTMLDivElement | null>(null);
  const svgRef = useRef<SVGSVGElement | null>(null);
  const [size, setSize] = useState<{ w: number; h: number }>({ w: 0, h: 0 });

  // Stage [8] — verifies the renderer actually mounted in every deployed bundle.
  useEffect(() => {
    // eslint-disable-next-line no-console
    console.info("[GSWING][8] Premium Renderer Mounted", {
      buildSha: __GSWING_BUILD_SHA__,
      buildTime: __GSWING_BUILD_TIME__,
      selectedHoleNumber,
      mapped_hole_id: mappedHole?.id ?? null,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Stage [9] — first time real player coordinates arrive.
  const playerLoggedRef = useRef(false);
  useEffect(() => {
    if (!playerPosition || playerLoggedRef.current) return;
    playerLoggedRef.current = true;
    // eslint-disable-next-line no-console
    console.info("[GSWING][9] Player Location Ready", {
      buildSha: __GSWING_BUILD_SHA__,
      playerPosition,
    });
  }, [playerPosition?.lat, playerPosition?.lng]); // eslint-disable-line react-hooks/exhaustive-deps

  // Track wrapper size for responsive projection.
  useEffect(() => {
    if (!wrapRef.current) return;
    const el = wrapRef.current;
    const ro = new ResizeObserver(() => {
      setSize({ w: el.clientWidth, h: el.clientHeight });
    });
    ro.observe(el);
    setSize({ w: el.clientWidth, h: el.clientHeight });
    return () => ro.disconnect();
  }, []);

  const usable = hasUsableHoleMapping(mappedHole);
  const premiumReady = useMemo(() => isPremiumReady(mappedHole), [mappedHole]);
  const missing = useMemo(() => missingPremiumLayers(mappedHole), [mappedHole]);
  const progress = useMemo(() => premiumProgress(mappedHole), [mappedHole]);
  const quality = useMemo(() => evaluateHoleQuality(mappedHole), [mappedHole]);
  // ─── Owned-geometry (V1 rendering platform) ──────────────────────────────
  // Additive: promote the legacy MappedHole into the new GswingHoleDefinition
  // and choose the framing path. When owned geometry isn't renderable we fall
  // straight back to the legacy buildHoleBounds path so nothing regresses.
  const gswingDefinition = useMemo(
    () => (mappedHole ? fromMappedHole(mappedHole) : null),
    [mappedHole],
  );
  const renderableSource = useMemo(
    () => getRenderableGeometrySource({ definition: gswingDefinition, legacy: mappedHole }),
    [gswingDefinition, mappedHole],
  );
  const useOwnedFraming = renderableSource === "gswing-definition" && !!gswingDefinition;
  // Hole-only bounds first — the hole must always fill the viewport,
  // even when the player is far from the course (e.g. sitting at home).
  const holeOnlyBounds = useMemo(
    () =>
      useOwnedFraming && gswingDefinition
        ? computePremiumBounds(gswingDefinition, null) ?? buildHoleBounds(mappedHole, null)
        : buildHoleBounds(mappedHole, null),
    [mappedHole, useOwnedFraming, gswingDefinition],
  );
  const includePlayer = useMemo(() => {
    if (!holeOnlyBounds || !playerPosition) return false;
    const latPad = 250 / 111000;
    const lngPad =
      250 / (111000 * Math.max(0.1, Math.cos((holeOnlyBounds.centerLat * Math.PI) / 180)));
    return (
      playerPosition.lat >= holeOnlyBounds.minLat - latPad &&
      playerPosition.lat <= holeOnlyBounds.maxLat + latPad &&
      playerPosition.lng >= holeOnlyBounds.minLng - lngPad &&
      playerPosition.lng <= holeOnlyBounds.maxLng + lngPad
    );
  }, [holeOnlyBounds, playerPosition?.lat, playerPosition?.lng]);
  const bounds = useMemo(
    () =>
      useOwnedFraming && gswingDefinition
        ? computePremiumBounds(gswingDefinition, includePlayer ? playerPosition : null) ??
          buildHoleBounds(mappedHole, includePlayer ? playerPosition : null)
        : buildHoleBounds(mappedHole, includePlayer ? playerPosition : null),
    [mappedHole, playerPosition?.lat, playerPosition?.lng, includePlayer, useOwnedFraming, gswingDefinition],
  );

  // Production diagnostics: proves which deployed bundle is rendering and
  // whether Premium is using mapped/OSM feature polygons or pure fallback.
  useEffect(() => {
    const bunkers = mappedHole?.hazards.filter((h) => h.type === "bunker").length ?? 0;
    const water = mappedHole?.hazards.filter(
      (h) => h.type === "water" || h.type === "penalty_area",
    ).length ?? 0;
    const hazardsWithPolygons = mappedHole?.hazards.filter((h) => h.polygon?.length).length ?? 0;
    const geometrySource = classifyGeometrySource(mappedHole);
    // eslint-disable-next-line no-console
    console.info("[gswing.premium-renderer] hole render", {
      buildSha: __GSWING_BUILD_SHA__,
      buildTime: __GSWING_BUILD_TIME__,
      selectedHoleNumber,
      mapped_hole_id: mappedHole?.id ?? null,
      hole_number: mappedHole?.holeNumber ?? null,
      autoGenerated: Boolean((mappedHole as (MappedHole & { autoGenerated?: boolean }) | null)?.autoGenerated),
      geometrySource,
      renderableSource,
      useOwnedFraming,
      premiumLayerOrder: PREMIUM_LAYER_ORDER,
      tees: mappedHole?.tees.length ?? 0,
      green_center: !!mappedHole?.green.center,
      green_front: !!mappedHole?.green.front,
      green_back: !!mappedHole?.green.back,
      green_polygon_pts: mappedHole?.green.polygon?.length ?? 0,
      pin: !!mappedHole?.pin,
      hazards_total: mappedHole?.hazards.length ?? 0,
      hazardsWithPolygons,
      bunkers,
      water_or_penalty: water,
      landing_zones: mappedHole?.landingZones.length ?? 0,
      layups: mappedHole?.layups.length ?? 0,
      doglegs: mappedHole?.doglegs.length ?? 0,
      hasUsableHoleMapping: usable,
      premiumReady,
      premiumProgress: progress,
      fairwayPolygonPts: polygonPointCount(mappedHole?.fairwayPolygon),
      teePolygonPts: polygonPointCount(mappedHole?.teePolygon),
      greenPolygonPts: polygonPointCount(mappedHole?.green.polygon),
      holeBoundaryPts: polygonPointCount(mappedHole?.holeBoundary),
      roughPolygonPts: polygonPointCount(mappedHole?.roughPolygon),
      cartPathPts: polygonPointCount(mappedHole?.cartPath),
      naLayers: mappedHole?.naLayers ?? [],
    });
  }, [mappedHole, selectedHoleNumber, usable, premiumReady, progress, renderableSource, useOwnedFraming]);

  const par = mappedHole?.par ?? null;

  // On-screen debug badge — proves at a glance whether Premium is rendering
  // real mapped polygons or falling back. Visible to every user; no DevTools
  // needed. Remove once mapped-data path is confirmed everywhere.
  const debugBadge = useMemo(() => {
    const geometrySource = classifyGeometrySource(mappedHole);
    const fairwayPolygonPts = polygonPointCount(mappedHole?.fairwayPolygon);
    const greenPolygonPts = polygonPointCount(mappedHole?.green.polygon);
    const hazardPolygons =
      mappedHole?.hazards.filter((h) => h.polygon?.length).length ?? 0;
    let boundsInputCount = 0;
    if (mappedHole) {
      boundsInputCount += mappedHole.tees.length;
      if (mappedHole.green.front) boundsInputCount += 1;
      if (mappedHole.green.center) boundsInputCount += 1;
      if (mappedHole.green.back) boundsInputCount += 1;
      if (mappedHole.green.polygon) boundsInputCount += mappedHole.green.polygon.length;
      if (mappedHole.fairwayPolygon) boundsInputCount += mappedHole.fairwayPolygon.length;
      if (mappedHole.teePolygon) boundsInputCount += mappedHole.teePolygon.length;
      if (mappedHole.holeBoundary) boundsInputCount += mappedHole.holeBoundary.length;
      for (const h of mappedHole.hazards) {
        if (h.polygon?.length) boundsInputCount += h.polygon.length;
        else if (h.center) boundsInputCount += 1;
      }
      if (includePlayer && playerPosition) boundsInputCount += 1;
    }
    return { geometrySource, fairwayPolygonPts, greenPolygonPts, hazardPolygons, boundsInputCount };
  }, [mappedHole, includePlayer, playerPosition?.lat, playerPosition?.lng]);
  const isMapped = debugBadge.geometrySource === "mapped-polygons";
  const isFallback = debugBadge.geometrySource === "auto-generated-fallback";
  const badgeTone = isMapped
    ? "border-emerald-400/60 text-emerald-200 bg-emerald-900/70"
    : isFallback
      ? "border-red-400/70 text-red-100 bg-red-900/70"
      : "border-amber-400/60 text-amber-100 bg-amber-900/70";
  const badgeLabel = isMapped
    ? "MAPPED"
    : isFallback
      ? "FALLBACK"
      : debugBadge.geometrySource === "auto-osm-polygons"
        ? "OSM"
        : "NONE";

  const projection: FittedProjection | null = useMemo(() => {
    if (!bounds || size.w < 20 || size.h < 20) return null;
    return fitHoleToViewport(bounds, {
      width: size.w,
      height: size.h,
      paddingPx: parPaddingPx(par),
      paddingBottomPx: PADDING + 280,
    });
  }, [bounds, size.w, size.h, par]);

  // Stage [10] — first successful paint with all data required.
  const renderCompleteRef = useRef(false);
  useEffect(() => {
    if (renderCompleteRef.current) return;
    if (!premiumReady || !projection || !mappedHole) return;
    renderCompleteRef.current = true;
    // eslint-disable-next-line no-console
    console.info("[GSWING][10] Render Complete", {
      buildSha: __GSWING_BUILD_SHA__,
      hole_number: mappedHole.holeNumber,
      geometrySource: classifyGeometrySource(mappedHole),
      hazards: mappedHole.hazards.length,
      premiumReady,
      bounds,
      projection: {
        scale: projection.scale,
        viewport: projection.viewport,
      },
    });
  }, [premiumReady, projection, mappedHole]);

  const handleTap = (e: React.MouseEvent<SVGSVGElement> | React.TouchEvent<SVGSVGElement>) => {
    if (!isMeasuring || !projection || !svgRef.current || !usable) return;
    const rect = svgRef.current.getBoundingClientRect();
    const t = "touches" in e ? e.changedTouches[0] : e;
    if (!t) return;
    const x = (t.clientX as number) - rect.left;
    const y = (t.clientY as number) - rect.top;
    const latlng = unprojectHoleCanvasToLatLng({ x, y }, projection);
    onMapTap(latlng);
  };

  return (
    <div
      ref={wrapRef}
      className="absolute inset-0 select-none"
      data-gswing-premium-renderer="true"
    >
      {/* Luxury terrain backdrop — deep emerald with painted vignette. */}
      <div className="absolute inset-0 bg-[radial-gradient(120%_100%_at_50%_40%,#16623f_0%,#0b4129_38%,#042214_72%,#01100a_100%)]" />
      <div className="absolute inset-0 bg-[radial-gradient(70%_45%_at_70%_15%,rgba(245,200,75,0.10)_0%,transparent_70%)] mix-blend-screen" />
      <div className="absolute inset-0 bg-[radial-gradient(45%_30%_at_15%_90%,rgba(0,0,0,0.55)_0%,transparent_70%)]" />
      {/* Per-hole personality tint — subtle atmospheric colour cast unique to each hole */}
      {(() => {
        const p = holePersonality(selectedHoleNumber);
        return (
          <div
            className="absolute inset-0 mix-blend-soft-light pointer-events-none"
            style={{ backgroundColor: p.tint, opacity: p.tintOpacity * 12 }}
          />
        );
      })()}

      {/* When a MappedHole exists but has no usable tee/green geometry
           (e.g. auto-synth returned a shell with no GolfAPI coordinates),
           show the mapping-required gate instead of a blank green screen.
           This satisfies the "Premium must never display an empty screen
           when geometry exists" acceptance criterion. */}
      {!usable && mappedHole ? (
        <PremiumMappingRequired
          selectedHoleNumber={selectedHoleNumber}
          missing={missing}
          progress={progress}
          isOwner={isOwner ?? false}
          onOpenMapper={onOpenMapper}
          onMarkLayerNa={onMarkLayerNa}
          onContinueSatellite={onContinueSatellite}
        />
      ) : !usable ? null : (
        <svg
          ref={svgRef}
          width={size.w || 1}
          height={size.h || 1}
          viewBox={`0 0 ${size.w || 1} ${size.h || 1}`}
          className={`absolute inset-0 h-full w-full ${
            isMeasuring ? "cursor-crosshair" : "cursor-default"
          }`}
          data-geometry-source={renderableSource}
          data-premium-layer-order={PREMIUM_LAYER_ORDER.join(",")}
          data-owned-framing={useOwnedFraming ? "true" : "false"}
          onClick={handleTap}
          onTouchEnd={handleTap}
        >
          <RendererDefs />
          {projection && mappedHole && (
            <HoleGeometryLayer
              hole={mappedHole}
              projection={projection}
              holeNumber={selectedHoleNumber}
              bounds={bounds}
            />
          )}
          {projection && playerPosition && includePlayer && (
            <PlayerMarker
              projection={projection}
              player={playerPosition}
              accuracy={gpsAccuracy}
            />
          )}
          {projection && measurementTarget && (playerPosition && includePlayer
            ? true
            : !!mappedHole?.tees?.[0]?.coordinate) && (
            <MeasurementLineLayer
              projection={projection}
              from={
                playerPosition && includePlayer
                  ? playerPosition
                  : (mappedHole!.tees[0].coordinate as LatLng)
              }
              to={measurementTarget}
              unit={unit}
            />
          )}
        </svg>
      )}

      {/* Hint chip when measuring with no GPS / no target */}
      {isMeasuring && usable && (
        <div className="pointer-events-none absolute left-1/2 bottom-3 -translate-x-1/2 rounded-full border border-gold/35 bg-black/65 px-3 py-1 text-[10px] uppercase tracking-[0.18em] text-gold backdrop-blur-md">
          {!playerPosition || !includePlayer
            ? measurementTarget
              ? "Measuring from tee"
              : "Tap the hole to measure (from tee)"
            : measurementTarget
              ? "Tap to update target"
              : "Tap the hole to measure"}
        </div>
      )}

      {/* Temporary on-screen Premium geometry debug badge — top-left,
          respects safe area, always visible so we can verify whether the
          renderer is using mapped polygons or fallback without DevTools. */}
      <div
        className={`pointer-events-none absolute left-2 rounded-lg border px-2 py-1.5 text-[10px] font-mono leading-tight backdrop-blur-md shadow-lg ${badgeTone}`}
        style={{ top: "calc(env(safe-area-inset-top, 0px) + 8px)" }}
        data-gswing-debug-badge="premium-geometry"
      >
        <div className="font-bold tracking-wider">H{selectedHoleNumber} · {badgeLabel}</div>
        <div>src: {debugBadge.geometrySource}</div>
        <div>fw: {debugBadge.fairwayPolygonPts} · gr: {debugBadge.greenPolygonPts}</div>
        <div>hz-poly: {debugBadge.hazardPolygons}</div>
        <div>bounds-in: {debugBadge.boundsInputCount}</div>
      </div>
    </div>
  );
}

/**
 * Premium Mapping Required gate. Replaces the old glowing centreline.
 * Lists exactly which premium visual layers are still missing for this
 * hole and directs the user to either map them or use Satellite mode.
 */
function PremiumMappingRequired({
  selectedHoleNumber,
  missing,
  progress,
  isOwner,
  onOpenMapper,
  onMarkLayerNa,
  onContinueSatellite,
}: {
  selectedHoleNumber: number;
  missing: ReturnType<typeof missingPremiumLayers>;
  progress: { done: number; total: number };
  isOwner: boolean;
  onOpenMapper?: () => void;
  onMarkLayerNa?: (layerKey: string) => void | Promise<void>;
  onContinueSatellite?: () => void;
}) {
  return (
    <div className="absolute inset-0 flex items-center justify-center px-6 text-center">
      <div className="max-w-sm rounded-2xl border border-gold/30 bg-black/65 px-5 py-5 backdrop-blur-md">
        <p className="text-[10px] uppercase tracking-[0.3em] text-gold-soft">G-Swing Premium</p>
        <h2 className="mt-1 font-serif text-xl text-gold">Hole {selectedHoleNumber}</h2>
        <p className="mt-1 text-[11px] uppercase tracking-[0.2em] text-gold">
          Premium Enhancement Studio
        </p>
        <p className="mt-3 text-[12px] leading-snug text-white/75">
          This hole renders automatically from GolfAPI.io — refine the visual
          layers below for a pixel-perfect illustration. GPS distances, Front /
          Center / Back, and measurements all work now.
        </p>
        <div className="mt-4 rounded-xl border border-white/10 bg-black/40 p-3 text-left">
          <div className="flex items-center justify-between text-[10px] uppercase tracking-[0.2em] text-gold-soft">
            <span>Enhancement layers</span>
            <span>{progress.done}/{progress.total}</span>
          </div>
          <ul className="mt-2 space-y-1 text-[12px] text-white/85">
            {missing.map((m) => (
              <li key={m.key} className="flex items-center gap-2">
                <span className="inline-block h-1.5 w-1.5 rounded-full bg-amber-300" />
                {m.label}
              </li>
            ))}
          </ul>
        </div>
        <p className="mt-3 text-[11px] leading-snug text-white/55">
          Switch to <span className="text-gold">Satellite</span> above at any
          time, or open the Enhancement Studio to refine individual polygons
          for this hole (or mark any layer not applicable).
        </p>
        {onContinueSatellite && (
          <button
            type="button"
            onClick={onContinueSatellite}
            className="mt-4 block w-full rounded-xl border border-gold/40 bg-black/55 px-3 py-2.5 font-hud text-[11px] font-semibold uppercase tracking-[0.22em] text-gold transition-all hover:bg-black/70 active:scale-[0.98]"
          >
            Continue with Satellite Only
          </button>
        )}
        {isOwner && (
          <div className="mt-4 rounded-xl border border-gold/40 bg-gradient-to-br from-emerald-950/60 via-black/50 to-emerald-950/60 p-3 text-left">
            <div className="mb-2 flex items-center justify-between">
              <span className="rounded-full border border-gold/40 bg-black/50 px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[0.22em] text-gold">
                Owner tools
              </span>
              <span className="text-[10px] uppercase tracking-[0.18em] text-gold-soft/80">
                Unlimited
              </span>
            </div>
            <p className="mb-3 text-[11px] leading-snug text-white/70">
              Refine visual layers to perfect the illustrated Premium view for
              this hole. Everything else already renders automatically.
            </p>
            <button
              type="button"
              onClick={() => onOpenMapper?.()}
              disabled={!onOpenMapper}
              className="block w-full rounded-xl bg-gold px-3 py-2.5 text-[11px] font-semibold uppercase tracking-[0.22em] text-black shadow-[0_0_18px_rgba(245,200,75,0.35)] transition-all active:scale-[0.98] disabled:opacity-50"
            >
              Open Enhancement Studio
            </button>
            {missing.length > 0 && onMarkLayerNa && (
              <div className="mt-2">
                <label className="text-[9px] uppercase tracking-[0.22em] text-gold-soft/80">
                  Mark layer not applicable
                </label>
                <select
                  defaultValue=""
                  onChange={(e) => {
                    const v = e.target.value;
                    if (!v) return;
                    void onMarkLayerNa(v);
                    e.currentTarget.value = "";
                  }}
                  className="mt-1 w-full rounded-lg border border-gold/30 bg-black/60 px-2 py-2 text-[11px] text-white/90 focus:border-gold focus:outline-none"
                >
                  <option value="" disabled>
                    Choose a layer…
                  </option>
                  {missing.map((m) => (
                    <option key={m.key} value={m.key}>
                      {m.label}
                    </option>
                  ))}
                </select>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

/** Shared SVG defs: gradients, filters, sand/tree patterns. */
function RendererDefs() {
  return (
    <defs>
      {/* Soft drop shadow under every premium feature */}
      <filter id="gs-shadow" x="-30%" y="-30%" width="160%" height="160%">
        <feGaussianBlur in="SourceAlpha" stdDeviation="2.4" />
        <feOffset dy="2" result="off" />
        <feComponentTransfer><feFuncA type="linear" slope="0.55" /></feComponentTransfer>
        <feMerge>
          <feMergeNode />
          <feMergeNode in="SourceGraphic" />
        </feMerge>
      </filter>
      {/* Softer, wider drop shadow used behind large landforms (fairway, boundary). */}
      <filter id="gs-shadow-soft" x="-40%" y="-40%" width="180%" height="180%">
        <feGaussianBlur in="SourceAlpha" stdDeviation="5" />
        <feOffset dy="3" result="off" />
        <feComponentTransfer><feFuncA type="linear" slope="0.45" /></feComponentTransfer>
        <feMerge>
          <feMergeNode />
          <feMergeNode in="SourceGraphic" />
        </feMerge>
      </filter>
      {/* Edge feather — used to soften polygon rims so auto-generated shapes
          don't look laser-cut. Applied via a lightweight blur+composite. */}
      <filter id="gs-feather" x="-10%" y="-10%" width="120%" height="120%">
        <feGaussianBlur stdDeviation="0.9" />
      </filter>
      {/* Bunker rim highlight — soft inner glow */}
      <filter id="gs-bunker-rim" x="-20%" y="-20%" width="140%" height="140%">
        <feGaussianBlur in="SourceAlpha" stdDeviation="1.2" result="b" />
        <feSpecularLighting in="b" surfaceScale="2" specularConstant="0.6" specularExponent="18" lightingColor="#fff5d6" result="spec">
          <feDistantLight azimuth="135" elevation="55" />
        </feSpecularLighting>
        <feComposite in="spec" in2="SourceAlpha" operator="in" result="specMasked" />
        <feMerge>
          <feMergeNode in="SourceGraphic" />
          <feMergeNode in="specMasked" />
        </feMerge>
      </filter>
      {/* Gentle inner highlight glow used by the green */}
      <filter id="gs-glow" x="-40%" y="-40%" width="180%" height="180%">
        <feGaussianBlur stdDeviation="3" result="b" />
        <feMerge>
          <feMergeNode in="b" />
          <feMergeNode in="SourceGraphic" />
        </feMerge>
      </filter>
      {/* Fairway gradient — bright sunlit center */}
      <radialGradient id="gs-fairway" cx="50%" cy="40%" r="65%">
        <stop offset="0%" stopColor="#6ad389" />
        <stop offset="55%" stopColor="#3aa765" />
        <stop offset="100%" stopColor="#1e6b3f" />
      </radialGradient>
      {/* Mowing stripes — alternating light/dark bands. Rotation is applied
          per-hole via a wrapping <pattern> with patternTransform inside
          HoleGeometryLayer so stripes follow tee→green bearing. */}
      <pattern id="gs-mow-base" width="14" height="14" patternUnits="userSpaceOnUse">
        <rect width="14" height="14" fill="transparent" />
        <rect x="0" y="0" width="14" height="7" fill="#ffffff" fillOpacity="0.07" />
        <rect x="0" y="7" width="14" height="7" fill="#000000" fillOpacity="0.05" />
      </pattern>
      {/* Finer mowing stripes for the green — perpendicular bands. */}
      <pattern id="gs-green-mow" width="8" height="8" patternUnits="userSpaceOnUse">
        <rect width="8" height="8" fill="transparent" />
        <rect x="0" y="0" width="8" height="4" fill="#ffffff" fillOpacity="0.09" />
        <rect x="0" y="4" width="8" height="4" fill="#000000" fillOpacity="0.06" />
      </pattern>
      <radialGradient id="gs-semirough" cx="50%" cy="50%" r="60%">
        <stop offset="0%" stopColor="#2f7e4d" />
        <stop offset="100%" stopColor="#16542f" />
      </radialGradient>
      <radialGradient id="gs-rough" cx="50%" cy="50%" r="60%">
        <stop offset="0%" stopColor="#1a4a2c" />
        <stop offset="100%" stopColor="#0a2c19" />
      </radialGradient>
      {/* Green gradient — bright manicured turf */}
      <radialGradient id="gs-green" cx="50%" cy="40%" r="65%">
        <stop offset="0%" stopColor="#9bf0b8" />
        <stop offset="55%" stopColor="#4ad17e" />
        <stop offset="100%" stopColor="#1c8048" />
      </radialGradient>
      {/* Directional green shading — used for front-to-back gradient */}
      <linearGradient id="gs-green-dir" x1="0%" y1="0%" x2="0%" y2="100%">
        <stop offset="0%" stopColor="#ffffff" stopOpacity="0.22" />
        <stop offset="50%" stopColor="#ffffff" stopOpacity="0" />
        <stop offset="100%" stopColor="#000000" stopOpacity="0.28" />
      </linearGradient>
      {/* Water gradient — deep teal with highlight */}
      <linearGradient id="gs-water" x1="0%" y1="0%" x2="0%" y2="100%">
        <stop offset="0%" stopColor="#5cc8e0" stopOpacity="0.95" />
        <stop offset="40%" stopColor="#1d6fb3" />
        <stop offset="100%" stopColor="#0b2c4f" />
      </linearGradient>
      {/* Water reflection sheen — thin diagonal highlight */}
      <linearGradient id="gs-water-sheen" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stopColor="#eaf9ff" stopOpacity="0.35" />
        <stop offset="35%" stopColor="#ffffff" stopOpacity="0" />
        <stop offset="70%" stopColor="#ffffff" stopOpacity="0" />
        <stop offset="100%" stopColor="#8fd6ff" stopOpacity="0.18" />
      </linearGradient>
      {/* Subtle ripple lines over water polygons. */}
      <pattern id="gs-water-ripple" width="18" height="10" patternUnits="userSpaceOnUse">
        <rect width="18" height="10" fill="transparent" />
        <path d="M0 5 Q 4.5 2 9 5 T 18 5" fill="none" stroke="#eaf9ff" strokeOpacity="0.28" strokeWidth="0.5" />
        <path d="M0 8 Q 4.5 6 9 8 T 18 8" fill="none" stroke="#ffffff" strokeOpacity="0.15" strokeWidth="0.4" />
      </pattern>
      {/* Bunker gradient — warm sand with rim */}
      <radialGradient id="gs-sand" cx="50%" cy="40%" r="60%">
        <stop offset="0%" stopColor="#fbeec3" />
        <stop offset="60%" stopColor="#e8d39a" />
        <stop offset="100%" stopColor="#b89a5f" />
      </radialGradient>
      {/* Sand stipple texture */}
      <pattern id="gs-sand-stipple" width="6" height="6" patternUnits="userSpaceOnUse">
        <rect width="6" height="6" fill="transparent" />
        <circle cx="1.5" cy="1.5" r="0.5" fill="#8a6f3a" opacity="0.45" />
        <circle cx="4.5" cy="3.5" r="0.4" fill="#8a6f3a" opacity="0.35" />
      </pattern>
      {/* Denser grain for larger bunkers */}
      <pattern id="gs-sand-grain" width="10" height="10" patternUnits="userSpaceOnUse">
        <rect width="10" height="10" fill="transparent" />
        <circle cx="2" cy="3" r="0.55" fill="#7d6432" opacity="0.4" />
        <circle cx="6" cy="7" r="0.5" fill="#7d6432" opacity="0.35" />
        <circle cx="8.5" cy="1.5" r="0.4" fill="#c9a869" opacity="0.55" />
        <circle cx="3.5" cy="8" r="0.35" fill="#c9a869" opacity="0.5" />
      </pattern>
      {/* Subtle green contour rings via mask */}
      <radialGradient id="gs-green-ring" cx="50%" cy="50%" r="50%">
        <stop offset="80%" stopColor="#ffffff" stopOpacity="0" />
        <stop offset="92%" stopColor="#ffffff" stopOpacity="0.25" />
        <stop offset="100%" stopColor="#ffffff" stopOpacity="0" />
      </radialGradient>
      {/* Tee gradient */}
      <linearGradient id="gs-tee" x1="0%" y1="0%" x2="0%" y2="100%">
        <stop offset="0%" stopColor="#2a1f00" />
        <stop offset="100%" stopColor="#120c00" />
      </linearGradient>
    </defs>
  );
}

function HoleGeometryLayer({
  hole,
  projection,
  holeNumber,
  bounds,
}: {
  hole: MappedHole;
  projection: FittedProjection;
  holeNumber: number;
  bounds: ReturnType<typeof buildHoleBounds>;
}) {
  const project = (p: { lat: number; lng: number }) =>
    projectLatLngToHoleCanvas(p, projection);

  const tee = hole.tees[0]?.coordinate ?? null;
  const greenCenter = hole.green.center ?? hole.pin?.coordinate ?? null;
  const greenFront = hole.green.front ?? null;
  const greenBack = hole.green.back ?? null;
  const greenPolygon = hole.green.polygon ?? null;
  const pin = hole.pin?.coordinate ?? null;

  // Premium illustration is now ENTIRELY polygon-driven. Centreline
  // corridor fallback has been removed — gating in the parent ensures
  // we never reach this layer without real polygons.
  const projectRing = (ring: Array<[number, number]>) =>
    ring.map(([lng, lat]) => project({ lat, lng }));

  const holeBoundaryPts = hole.holeBoundary ? projectRing(hole.holeBoundary) : null;
  const fairwayPts = hole.fairwayPolygon ? projectRing(hole.fairwayPolygon) : null;
  const teePolyPts = hole.teePolygon ? projectRing(hole.teePolygon) : null;
  const roughPts = hole.roughPolygon ? projectRing(hole.roughPolygon) : null;
  const cartPathPts = hole.cartPath ? projectRing(hole.cartPath) : null;

  // Mowing angle: tee → green centroid, in screen degrees.
  let mowAngleDeg = 0;
  if (tee && greenCenter) {
    const t = project(tee);
    const g = project(greenCenter);
    mowAngleDeg = (Math.atan2(g.y - t.y, g.x - t.x) * 180) / Math.PI;
  }
  // Sanitised id fragment for unique per-hole defs.
  const uid = (hole.id || `h${hole.holeNumber}`).replace(/[^a-zA-Z0-9_-]/g, "_");
  const mowPatternId = `gs-mow-${uid}`;
  const mowPerpPatternId = `gs-mow-perp-${uid}`;
  const greenDirId = `gs-green-dir-${uid}`;
  const holeClipId = `gs-hole-clip-${uid}`;

  // Compute the water clipping rect in SVG canvas space.
  // Use the hole bounding box + a generous margin (75px) so water that
  // legitimately bleeds slightly outside the fairway corridor is still
  // visible, while large shared lakes that span multiple holes are cut off.
  const WATER_CLIP_MARGIN = 75; // px on each side
  const clipRect = bounds ? (() => {
    const tl = project({ lat: bounds.maxLat, lng: bounds.minLng });
    const br = project({ lat: bounds.minLat, lng: bounds.maxLng });
    return {
      x: tl.x - WATER_CLIP_MARGIN,
      y: tl.y - WATER_CLIP_MARGIN,
      w: (br.x - tl.x) + WATER_CLIP_MARGIN * 2,
      h: (br.y - tl.y) + WATER_CLIP_MARGIN * 2,
    };
  })() : null;

  // Green radius fallback only for the legacy ring overlay; if no polygon
  // we still draw the front/back-derived footprint as a soft halo.
  let greenRadiusPx = 28;
  if (greenFront && greenBack) {
    const a = project(greenFront);
    const b = project(greenBack);
    greenRadiusPx = Math.max(18, Math.hypot(a.x - b.x, a.y - b.y) / 2);
  }

  return (
    <g>
      {/* Per-hole dynamic defs: rotated mowing patterns + oriented green shading + water clip. */}
      <defs>
        <pattern
          id={mowPatternId}
          width="18"
          height="18"
          patternUnits="userSpaceOnUse"
          patternTransform={`rotate(${mowAngleDeg.toFixed(1)})`}
        >
          <rect width="18" height="18" fill="transparent" />
          <rect x="0" y="0" width="18" height="9" fill="#ffffff" fillOpacity="0.08" />
          <rect x="0" y="9" width="18" height="9" fill="#000000" fillOpacity="0.07" />
        </pattern>
        <pattern
          id={mowPerpPatternId}
          width="10"
          height="10"
          patternUnits="userSpaceOnUse"
          patternTransform={`rotate(${(mowAngleDeg + 90).toFixed(1)})`}
        >
          <rect width="10" height="10" fill="transparent" />
          <rect x="0" y="0" width="10" height="5" fill="#ffffff" fillOpacity="0.11" />
          <rect x="0" y="5" width="10" height="5" fill="#000000" fillOpacity="0.07" />
        </pattern>
        <linearGradient
          id={greenDirId}
          gradientUnits="userSpaceOnUse"
          x1={greenFront ? project(greenFront).x : 0}
          y1={greenFront ? project(greenFront).y : 0}
          x2={greenBack ? project(greenBack).x : 0}
          y2={greenBack ? project(greenBack).y : 0}
        >
          <stop offset="0%" stopColor="#ffffff" stopOpacity="0.22" />
          <stop offset="55%" stopColor="#ffffff" stopOpacity="0" />
          <stop offset="100%" stopColor="#04140a" stopOpacity="0.35" />
        </linearGradient>
        {/* Water viewport clip — keeps shared multi-hole lakes confined to the
             active hole frame. Feathered by a generous margin so natural
             water that legitimately sits at the edge is not hard-cut. */}
        {clipRect && (
          <clipPath id={holeClipId}>
            <rect
              x={clipRect.x}
              y={clipRect.y}
              width={clipRect.w}
              height={clipRect.h}
            />
          </clipPath>
        )}
      </defs>
      {/* Hole boundary — painted as the outer rough mass for depth. */}
      {holeBoundaryPts && holeBoundaryPts.length >= 3 && (
        <g filter="url(#gs-shadow-soft)" data-layer="rough">
          <path
            d={smoothRingPath(holeBoundaryPts)}
            fill="url(#gs-rough)"
            fillOpacity={0.95}
            stroke="#0a2c19"
            strokeOpacity={0.7}
            strokeWidth={1}
          />
          {/* Feathered rim so the boundary blends into the terrain */}
          <path
            d={smoothRingPath(holeBoundaryPts)}
            fill="none"
            stroke="#031a0f"
            strokeOpacity={0.55}
            strokeWidth={6}
            filter="url(#gs-feather)"
          />
        </g>
      )}

      {/* Explicit rough polygon overlay (if mapped separately). */}
      {roughPts && roughPts.length >= 3 && (
        <g data-layer="rough">
          <path
            d={smoothRingPath(roughPts)}
            fill="url(#gs-semirough)"
            fillOpacity={0.85}
            stroke="#16542f"
            strokeOpacity={0.55}
            strokeWidth={0.8}
          />
        </g>
      )}

      {/* Manicured fairway — organic polygon from mapping. */}
      {fairwayPts && fairwayPts.length >= 3 && (
        <g filter="url(#gs-shadow-soft)" data-layer="fairway">
          {/* Feathered semi-rough halo just outside the fairway */}
          <path
            d={smoothRingPath(fairwayPts)}
            fill="url(#gs-semirough)"
            fillOpacity={0.5}
            stroke="none"
            transform="scale(1.035)"
            style={{ transformOrigin: "center", transformBox: "fill-box" } as React.CSSProperties}
            filter="url(#gs-feather)"
          />
          {/* Base fairway turf */}
          <path
            d={smoothRingPath(fairwayPts)}
            fill="url(#gs-fairway)"
            stroke="#1e6b3f"
            strokeOpacity={0.55}
            strokeWidth={1}
          />
          {/* Mowing stripes rotated along tee→green bearing. */}
          <path
            d={smoothRingPath(fairwayPts)}
            fill={`url(#${mowPatternId})`}
            stroke="none"
          />
          {/* Sunlit highlight ribbon */}
          <path
            d={smoothRingPath(fairwayPts)}
            fill="none"
            stroke="#dcffe8"
            strokeOpacity={0.15}
            strokeWidth={1.4}
            filter="url(#gs-feather)"
          />
        </g>
      )}

      {/* Cart path */}
      {cartPathPts && cartPathPts.length >= 2 && (
        <g data-layer="cart-paths">
          <path
            d={cartPathPts
              .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`)
              .join(" ")}
            fill="none"
            stroke="#d8c8a3"
            strokeOpacity={0.7}
            strokeWidth={2.5}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeDasharray="1 0"
          />
        </g>
      )}

      {/* ─── Hazards ────────────────────────────────────────────────────────
           Water is clipped to the hole corridor viewport + a generous margin
           so shared lake polygons (H1/H3, H5/H7/H9, H6/H8) do not spill
           beyond the active hole's frame. Bunkers and trees are NOT clipped
           — they are always within reasonable range of the fairway.
           ─────────────────────────────────────────────────────────────────── */}
      <g data-layer="hazards" data-layer-composite="water,bunkers,trees">
        {hole.hazards
          .slice()
          .sort((a, b) => layerOrder(a.type) - layerOrder(b.type))
          .map((h) => (
            <HazardShape
              key={h.id}
              hazard={h}
              projection={projection}
              holeNumber={holeNumber}
              holeClipId={holeClipId}
            />
          ))}
      </g>

      {/* Landing zones — premium dashed rings with label */}
      {hole.landingZones.length > 0 && (
        <g data-layer="labels" data-label-kind="landing-zones">
          {hole.landingZones.map((z) => {
        const p = project(z.coordinate);
        const r = 22;
        return (
          <g key={z.id}>
            <circle cx={p.x} cy={p.y} r={r} fill="#F5C84B" fillOpacity={0.04} stroke="#F5C84B" strokeOpacity={0.45} strokeWidth={1} strokeDasharray="2 4" />
            <circle cx={p.x} cy={p.y} r={2} fill="#F5C84B" />
            <text x={p.x} y={p.y - r - 4} fill="#F5C84B" fontSize="9" textAnchor="middle" opacity={0.85} fontFamily="ui-serif, Georgia">
              {z.name || "Landing"}
            </text>
          </g>
        );
          })}
        </g>
      )}

      {/* Layups */}
      {hole.layups.length > 0 && (
        <g data-layer="markers" data-marker-kind="layups">
          {hole.layups.map((l) => {
        const p = project(l.coordinate);
        return (
          <g key={l.id}>
            <circle cx={p.x} cy={p.y} r={11} fill="#0b2a18" stroke="#F5C84B" strokeOpacity={0.85} strokeDasharray="3 3" />
            <text x={p.x} y={p.y + 3} fill="#F5C84B" fontSize="9" textAnchor="middle" fontFamily="ui-serif, Georgia" fontWeight={600}>L</text>
            <text x={p.x} y={p.y + 22} fill="#F5C84B" fontSize="9" textAnchor="middle" fontFamily="ui-serif, Georgia">
              {l.name}
            </text>
          </g>
        );
          })}
        </g>
      )}

      {/* Green — uses mapped polygon when available, organic shape */}
      <g data-layer="green">
        {greenPolygon && greenPolygon.length >= 3 ? (
          <GreenPolygon
            polygon={greenPolygon}
            project={project}
            greenDirId={greenDirId}
          />
        ) : (
          greenCenter && (
            <GreenFallback
              center={project(greenCenter)}
              radiusPx={greenRadiusPx}
            />
          )
        )}
      </g>

      {/* Pin / flag — focal point of the entire hole illustration */}
      {pin && (() => {
        const p = project(pin);
        return (
          <g data-layer="pin">
            {/* Pin glow halo — subtle golden bloom so the pin is immediately visible */}
            <circle cx={p.x} cy={p.y} r={18} fill="#F5C84B" fillOpacity={0.07} filter="url(#gs-glow)" />
            {/* Ground shadow cone under the pin */}
            <ellipse cx={p.x + 2} cy={p.y + 2} rx={5} ry={2.5} fill="#000" opacity={0.32} filter="url(#gs-feather)" />
            {/* Flagstick */}
            <line x1={p.x} y1={p.y} x2={p.x} y2={p.y - 28}
              stroke="#f7f3e5" strokeWidth={1.6} strokeLinecap="round" />
            {/* Flag */}
            <polygon
              points={`${p.x},${p.y - 28} ${p.x + 15},${p.y - 22} ${p.x},${p.y - 16}`}
              fill="#F5C84B"
              stroke="#8a6a18"
              strokeWidth={0.7}
            />
            {/* Cup ring at base */}
            <circle cx={p.x} cy={p.y} r={3.2} fill="#fff" stroke="#1a1a1a" strokeWidth={0.8} />
            <circle cx={p.x} cy={p.y} r={1.4} fill="#000" opacity={0.5} />
          </g>
        );
      })()}

      {/* Tee — prefer polygon, fall back to icon */}
      {teePolyPts && teePolyPts.length >= 3 ? (
        <g filter="url(#gs-shadow)" data-layer="tee">
          <path
            d={ringPath(teePolyPts)}
            fill="url(#gs-tee)"
            stroke="#F5C84B"
            strokeOpacity={0.85}
            strokeWidth={1.2}
          />
        </g>
      ) : tee && (() => {
        const t = project(tee);
        return (
          <g filter="url(#gs-shadow)" data-layer="tee">
            <rect x={t.x - 14} y={t.y - 9} width={28} height={18} rx={4} fill="url(#gs-tee)" stroke="#F5C84B" strokeWidth={1.4} />
            <circle cx={t.x - 7} cy={t.y} r={1.6} fill="#F5C84B" />
            <circle cx={t.x + 7} cy={t.y} r={1.6} fill="#F5C84B" />
            <text x={t.x} y={t.y + 22} fill="#F5C84B" fontSize="9" textAnchor="middle" fontFamily="ui-serif, Georgia" letterSpacing="2">TEE</text>
          </g>
        );
      })()}
    </g>
  );
}

function layerOrder(t: HazardGeometry["type"]): number {
  // Larger features painted first so smaller ones sit on top.
  switch (t) {
    case "trees":
    case "rough":
    case "out_of_bounds":
    case "waste_area":
      return 0;
    case "water":
      return 1;
    case "penalty_area":
      return 2;
    case "bunker":
      return 3;
    default:
      return 1;
  }
}

/** Mapped green polygon — smoothed organic shape with rim & highlight. */
function GreenPolygon({
  polygon,
  project,
  greenDirId,
}: {
  polygon: Array<[number, number]>;
  project: (p: { lat: number; lng: number }) => { x: number; y: number };
  greenDirId: string;
}) {
  const pts = polygon.map(([lng, lat]) => project({ lat, lng }));
  if (pts.length < 3) return null;
  let cx = 0, cy = 0;
  for (const p of pts) { cx += p.x; cy += p.y; }
  cx /= pts.length; cy /= pts.length;
  let rMax = 0;
  for (const p of pts) rMax = Math.max(rMax, Math.hypot(p.x - cx, p.y - cy));
  const path = smoothRingPath(pts);
  const clipId = `${greenDirId}-clip`;
  return (
    <g filter="url(#gs-shadow-soft)">
      <defs>
        <clipPath id={clipId}>
          <path d={path} />
        </clipPath>
      </defs>
      {/* Wide feathered fringe / collar — dark surround that makes the green pop */}
      <path d={path} fill="#0c3020" stroke="#0c3020" strokeWidth={16} strokeLinejoin="round" opacity={0.98} filter="url(#gs-feather)" />
      {/* Collar ring — slightly lighter than rough, slightly darker than green */}
      <path d={path} fill="none" stroke="#1a5c38" strokeOpacity={0.85} strokeWidth={5} />
      {/* Manicured turf */}
      <path d={path} fill="url(#gs-green)" stroke="#a8efc6" strokeOpacity={0.55} strokeWidth={1.1} />
      {/* Perpendicular mowing bands, clipped to the green */}
      <g clipPath={`url(#${clipId})`}>
        <rect x={cx - rMax - 10} y={cy - rMax - 10} width={rMax * 2 + 20} height={rMax * 2 + 20} fill="url(#gs-green-mow)" opacity={0.92} />
      </g>
      {/* Directional shading (front→back) */}
      <path d={path} fill={`url(#${greenDirId})`} />
      {/* Contour rings for depth — organic green surface feel */}
      <circle cx={cx} cy={cy} r={Math.max(4, rMax * 0.65)} fill="url(#gs-green-ring)" />
      <circle cx={cx} cy={cy} r={Math.max(3, rMax * 0.42)} fill="none" stroke="#ffffff" strokeOpacity={0.1} strokeWidth={0.8} />
      {/* Cup shadow — small dark ring at the centre to imply the hole */}
      <circle cx={cx} cy={cy} r={Math.max(2.5, rMax * 0.08)} fill="#041a0d" opacity={0.65} />
      <circle cx={cx} cy={cy} r={Math.max(2, rMax * 0.06)} fill="#000" opacity={0.4} />
      {/* Highlight rim — bright edge catches the sun */}
      <path d={path} fill="none" stroke="#d8ffe8" strokeOpacity={0.38} strokeWidth={1} filter="url(#gs-feather)" />
    </g>
  );
}

function GreenFallback({
  center,
  radiusPx,
}: {
  center: { x: number; y: number };
  radiusPx: number;
}) {
  return (
    <g filter="url(#gs-shadow)">
      <circle cx={center.x} cy={center.y} r={radiusPx + 6} fill="#0e3a25" />
      <circle cx={center.x} cy={center.y} r={radiusPx} fill="url(#gs-green)" stroke="#a8efc6" strokeOpacity={0.4} strokeWidth={1} />
      <circle cx={center.x} cy={center.y} r={radiusPx * 0.55} fill="url(#gs-green-ring)" />
    </g>
  );
}

function HazardShape({
  hazard,
  projection,
  holeNumber,
  holeClipId,
}: {
  hazard: HazardGeometry;
  projection: FittedProjection;
  holeNumber: number;
  holeClipId: string;
}) {
  const project = (p: { lat: number; lng: number }) =>
    projectLatLngToHoleCanvas(p, projection);
  const c = project(calculateFeatureCentroid(hazard));
  const polyPts =
    hazard.polygon && hazard.polygon.length >= 3
      ? hazard.polygon.map(([lng, lat]) => project({ lat, lng }))
      : null;

  switch (hazard.type) {
    case "water":
    case "penalty_area":
      // Water is always clipped to the hole viewport so shared multi-hole
      // lakes don't dominate frames they don't belong to.
      return (
        <g clipPath={`url(#${holeClipId})`}>
          <WaterFeature points={polyPts} center={c} />
        </g>
      );
    case "bunker":
      return <BunkerFeature points={polyPts} center={c} hazardId={hazard.id} />;
    case "trees":
      return <TreeFeature points={polyPts} center={c} projection={projection} holeNumber={holeNumber} hazardId={hazard.id} />;
    case "rough":
      return <RoughFeature points={polyPts} center={c} />;
    case "out_of_bounds":
      return <OutOfBoundsFeature points={polyPts} center={c} />;
    case "waste_area":
      return <WasteFeature points={polyPts} center={c} />;
    default:
      return <BunkerFeature points={polyPts} center={c} hazardId={hazard.id} />;
  }
}

function ringPath(pts: { x: number; y: number }[]): string {
  return `${pts
    .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`)
    .join(" ")} Z`;
}

/**
 * Smoothed closed ring using Catmull-Rom → cubic Bézier conversion.
 * Produces softer, organic edges — critical for making auto-generated
 * bunker / water / boundary polygons look hand-drawn instead of faceted.
 * Falls back to a straight ring for <4 points.
 */
function smoothRingPath(pts: { x: number; y: number }[], tension = 0.5): string {
  const n = pts.length;
  if (n < 4) return ringPath(pts);
  const k = (1 - tension) / 6;
  const p = (i: number) => pts[((i % n) + n) % n];
  let d = `M ${p(0).x.toFixed(1)} ${p(0).y.toFixed(1)}`;
  for (let i = 0; i < n; i++) {
    const p0 = p(i - 1);
    const p1 = p(i);
    const p2 = p(i + 1);
    const p3 = p(i + 2);
    const c1x = p1.x + (p2.x - p0.x) * k;
    const c1y = p1.y + (p2.y - p0.y) * k;
    const c2x = p2.x - (p3.x - p1.x) * k;
    const c2y = p2.y - (p3.y - p1.y) * k;
    d += ` C ${c1x.toFixed(1)} ${c1y.toFixed(1)}, ${c2x.toFixed(1)} ${c2y.toFixed(1)}, ${p2.x.toFixed(1)} ${p2.y.toFixed(1)}`;
  }
  return `${d} Z`;
}

/** Cheap deterministic PRNG for seeded per-hazard variation. */
function seededRand(seed: string): () => number {
  let s = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    s ^= seed.charCodeAt(i);
    s = Math.imul(s, 16777619);
  }
  return () => {
    s ^= s << 13;
    s ^= s >>> 17;
    s ^= s << 5;
    return ((s >>> 0) % 100000) / 100000;
  };
}

function WaterFeature({ points, center }: { points: { x: number; y: number }[] | null; center: { x: number; y: number } }) {
  if (points) {
    const path = smoothRingPath(points, 0.45);
    // Compute centroid for highlight placement
    let cx = 0, cy = 0;
    for (const p of points) { cx += p.x; cy += p.y; }
    cx /= points.length; cy /= points.length;
    return (
      <g filter="url(#gs-shadow-soft)">
        {/* Base fill */}
        <path d={path} fill="url(#gs-water)" />
        {/* Ripple texture */}
        <path d={path} fill="url(#gs-water-ripple)" opacity={0.65} />
        {/* Directional sheen */}
        <path d={path} fill="url(#gs-water-sheen)" opacity={0.85} />
        {/* Defined shoreline — bright inner edge for clarity */}
        <path d={path} fill="none" stroke="#b8eaff" strokeOpacity={0.7} strokeWidth={1.2} />
        {/* Soft outer glow so edge feathers naturally into rough */}
        <path d={path} fill="none" stroke="#9adcff" strokeOpacity={0.3} strokeWidth={4}
          filter="url(#gs-feather)" />
        {/* Specular highlight — bright white patch near top-left (sun position) */}
        <ellipse
          cx={cx - Math.abs(cx - points[0].x) * 0.25}
          cy={cy - Math.abs(cy - points[0].y) * 0.2}
          rx={Math.max(8, Math.abs(cx - points[0].x) * 0.3)}
          ry={Math.max(4, Math.abs(cy - points[0].y) * 0.15)}
          fill="#eaf9ff"
          opacity={0.22}
        />
      </g>
    );
  }
  return (
    <g filter="url(#gs-shadow-soft)">
      <ellipse cx={center.x} cy={center.y} rx={28} ry={18} fill="url(#gs-water)" stroke="#b8eaff" strokeOpacity={0.65} strokeWidth={1.2} />
      <ellipse cx={center.x} cy={center.y} rx={28} ry={18} fill="url(#gs-water-ripple)" opacity={0.6} />
      <ellipse cx={center.x} cy={center.y} rx={28} ry={18} fill="url(#gs-water-sheen)" opacity={0.8} />
      <ellipse cx={center.x - 6} cy={center.y - 5} rx={14} ry={5} fill="#cfeeff" opacity={0.28} />
    </g>
  );
}

function BunkerFeature({ points, center, hazardId }: { points: { x: number; y: number }[] | null; center: { x: number; y: number }; hazardId: string }) {
  if (points) {
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const p of points) {
      if (p.x < minX) minX = p.x; if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y; if (p.y > maxY) maxY = p.y;
    }
    const spanX = maxX - minX;
    const spanY = maxY - minY;
    const large = Math.max(spanX, spanY) > 60;
    // Detect long strip bunkers (aspect ratio > 3.5:1). Instead of rendering
    // as one ribbon, split into N visually-separated oval bunker sections.
    const aspectRatio = Math.max(spanX, spanY) / Math.max(1, Math.min(spanX, spanY));
    const isStrip = aspectRatio > 3.5 && Math.max(spanX, spanY) > 80;
    if (isStrip) {
      // Determine if the strip is more horizontal or vertical
      const horizontal = spanX > spanY;
      const mainSpan = horizontal ? spanX : spanY;
      // Split into 3 sections with gaps between them (25% gap of each section)
      const numSections = 3;
      const sectionLen = mainSpan / numSections;
      const gapFrac = 0.18; // 18% gap between sections
      const rng = seededRand(hazardId + ":strip");
      const sections = Array.from({ length: numSections }, (_, i) => {
        const sectionCx = horizontal
          ? minX + sectionLen * i + sectionLen * 0.5
          : (minX + maxX) / 2 + (rng() - 0.5) * (spanX * 0.3);
        const sectionCy = horizontal
          ? (minY + maxY) / 2 + (rng() - 0.5) * (spanY * 0.3)
          : minY + sectionLen * i + sectionLen * 0.5;
        const rx = horizontal
          ? sectionLen * (1 - gapFrac) * 0.5
          : Math.max(6, spanX * 0.5 * (0.7 + rng() * 0.3));
        const ry = horizontal
          ? Math.max(6, spanY * 0.5 * (0.7 + rng() * 0.3))
          : sectionLen * (1 - gapFrac) * 0.5;
        return { cx: sectionCx, cy: sectionCy, rx, ry };
      });
      return (
        <g filter="url(#gs-shadow)">
          {sections.map((s, i) => (
            <g key={i} filter="url(#gs-bunker-rim)">
              <ellipse cx={s.cx + 1} cy={s.cy + 1.5} rx={s.rx} ry={s.ry} fill="#3a2a10" opacity={0.45} filter="url(#gs-feather)" />
              <ellipse cx={s.cx} cy={s.cy} rx={s.rx} ry={s.ry}
                fill="url(#gs-sand)" stroke="#a87f3a" strokeOpacity={0.65} strokeWidth={0.8} />
              <ellipse cx={s.cx} cy={s.cy} rx={s.rx} ry={s.ry}
                fill="url(#gs-sand-stipple)" opacity={0.55} />
              <ellipse cx={s.cx} cy={s.cy} rx={s.rx} ry={s.ry}
                fill="none" stroke="#fff3c6" strokeOpacity={0.3} strokeWidth={0.5} filter="url(#gs-feather)" />
            </g>
          ))}
        </g>
      );
    }
    // Standard bunker polygon render
    const path = smoothRingPath(points, 0.4);
    return (
      <g filter="url(#gs-shadow)">
        <path d={path} fill="#3a2a10" opacity={0.5} transform="translate(1.2,2)" filter="url(#gs-feather)" />
        <path d={path} fill="url(#gs-sand)" stroke="#a87f3a" strokeOpacity={0.65} strokeWidth={0.8} filter="url(#gs-bunker-rim)" />
        <path d={path} fill={large ? "url(#gs-sand-grain)" : "url(#gs-sand-stipple)"} opacity={0.55} />
        <path d={path} fill="none" stroke="#fff3c6" strokeOpacity={0.35} strokeWidth={0.5} filter="url(#gs-feather)" />
      </g>
    );
  }
  return (
    <g filter="url(#gs-shadow)">
      <g filter="url(#gs-bunker-rim)">
        <ellipse cx={center.x - 5} cy={center.y + 1} rx={16} ry={10} fill="url(#gs-sand)" stroke="#a87f3a" strokeOpacity={0.7} strokeWidth={0.8} />
        <ellipse cx={center.x + 7} cy={center.y - 3} rx={11} ry={7} fill="url(#gs-sand)" stroke="#a87f3a" strokeOpacity={0.6} strokeWidth={0.8} />
      </g>
      <ellipse cx={center.x - 5} cy={center.y + 1} rx={16} ry={10} fill="url(#gs-sand-grain)" opacity={0.5} />
    </g>
  );
}

// Three palm/desert-golf tree palettes for variety. Each entry is
// [baseHex, highlightHex, specularHex].
const TREE_PALETTES: [string, string, string][] = [
  ["#0d3a22", "#1b6a3c", "#a8e6bf"],  // deep emerald (most common)
  ["#1a4a18", "#2d7a28", "#b8f0a0"],  // bright lime-green
  ["#0a2e1f", "#145c38", "#80d4a8"],  // muted teal-green
  ["#263a14", "#4a7520", "#c8e890"],  // olive-khaki (desert palms)
];

function TreeFeature({
  points,
  center,
  projection,
  holeNumber,
  hazardId,
}: {
  points: { x: number; y: number }[] | null;
  center: { x: number; y: number };
  projection: FittedProjection;
  holeNumber: number;
  hazardId: string;
}) {
  // meters → px, same conversion PlayerMarker uses for the accuracy ring.
  const metersToPx = projection.scale / 111000;
  // Seed from hazard id for stable, unique scatter per cluster.
  const rand = seededRand(`${hazardId}:${holeNumber}:trees`);

  // Bounding box + point-in-polygon test, in px space.
  const poly = points && points.length >= 3 ? points : null;
  let minX = center.x - 14,
    maxX = center.x + 14,
    minY = center.y - 14,
    maxY = center.y + 14;
  if (poly) {
    minX = Infinity; maxX = -Infinity; minY = Infinity; maxY = -Infinity;
    for (const p of poly) {
      if (p.x < minX) minX = p.x;
      if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.y > maxY) maxY = p.y;
    }
  }
  const inPoly = (x: number, y: number): boolean => {
    if (!poly) {
      const dx = x - center.x;
      const dy = y - center.y;
      return dx * dx + dy * dy <= 14 * 14;
    }
    let inside = false;
    for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
      const xi = poly[i].x, yi = poly[i].y;
      const xj = poly[j].x, yj = poly[j].y;
      const intersect = ((yi > y) !== (yj > y)) &&
        (x < ((xj - xi) * (y - yi)) / (yj - yi + 1e-9) + xi);
      if (intersect) inside = !inside;
    }
    return inside;
  };

  // Scatter trees inside the cluster polygon — count scales with the
  // polygon's on-screen area so large imagery-derived tree masses stay
  // dense while small clusters keep 5–9 trees.
  const bboxArea = Math.max(1, (maxX - minX) * (maxY - minY));
  const target = Math.max(
    5 + Math.floor(rand() * 5),
    Math.min(42, Math.round((bboxArea * 0.62) / 260)),
  );
  const scattered: Array<{ x: number; y: number; r: number }> = [];
  let attempts = 0;
  while (scattered.length < target && attempts < target * 40) {
    attempts++;
    const x = minX + rand() * (maxX - minX);
    const y = minY + rand() * (maxY - minY);
    if (!inPoly(x, y)) continue;
    const rMeters = 2.5 + rand() * 2;
    const r = Math.max(3, Math.min(14, rMeters * metersToPx));
    scattered.push({ x, y, r });
  }
  // Fallback so we always draw at least one tree even in tiny clusters.
  if (scattered.length === 0) {
    scattered.push({ x: center.x, y: center.y, r: Math.max(3, Math.min(14, 3 * metersToPx)) });
  }

  // Pre-pick palette for this cluster (stable, based on seeded rand)
  const paletteIdx = Math.floor(rand() * TREE_PALETTES.length);

  return (
    <g filter="url(#gs-shadow)">
      {scattered.map((p, i) => {
        const lightness = 0.72 + rand() * 0.56;
        // Occasionally use a neighbouring palette for intra-cluster variety
        const thisPalette = TREE_PALETTES[(paletteIdx + (rand() > 0.78 ? 1 : 0)) % TREE_PALETTES.length];
        const base = shadeHex(thisPalette[0], lightness);
        const hi   = shadeHex(thisPalette[1], lightness);
        const spec = thisPalette[2];
        const r = p.r;
        // Taller trees get a tiny trunk nub for silhouette realism
        const showTrunk = r > 5.5;
        return (
          <g key={i}>
            {/* Drop shadow */}
            <ellipse cx={p.x + r * 0.25} cy={p.y + r * 0.55} rx={r * 0.85} ry={r * 0.3} fill="#01090504" opacity={0.65} />
            {/* Trunk */}
            {showTrunk && (
              <rect
                x={p.x - 0.8}
                y={p.y + r * 0.45}
                width={1.6}
                height={r * 0.55}
                rx={0.8}
                fill="#3a2008"
                opacity={0.75}
              />
            )}
            {/* Canopy base */}
            <circle cx={p.x} cy={p.y} r={r} fill={base} />
            {/* Inner highlight dome */}
            <circle cx={p.x - r * 0.32} cy={p.y - r * 0.36} r={r * 0.55} fill={hi} opacity={0.88} />
            {/* Specular tip */}
            <circle cx={p.x - r * 0.52} cy={p.y - r * 0.52} r={r * 0.2} fill={spec} opacity={0.48} />
          </g>
        );
      })}
    </g>
  );
}

/** Multiply a hex color's channels by `mul`, clamped to 0-255. */
function shadeHex(hex: string, mul: number): string {
  const h = hex.replace("#", "");
  const r = Math.min(255, Math.round(parseInt(h.slice(0, 2), 16) * mul));
  const g = Math.min(255, Math.round(parseInt(h.slice(2, 4), 16) * mul));
  const b = Math.min(255, Math.round(parseInt(h.slice(4, 6), 16) * mul));
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

function seedCluster(center: { x: number; y: number }, n: number): { x: number; y: number }[] {
  const out: { x: number; y: number }[] = [];
  let s = 1;
  for (let i = 0; i < n; i++) {
    s = (s * 9301 + 49297) % 233280;
    const ang = (s / 233280) * Math.PI * 2;
    const rad = 6 + (s % 26);
    out.push({ x: center.x + Math.cos(ang) * rad, y: center.y + Math.sin(ang) * rad * 0.8 });
  }
  return out;
}

function RoughFeature({ points, center }: { points: { x: number; y: number }[] | null; center: { x: number; y: number } }) {
  if (points) {
    return <path d={smoothRingPath(points)} fill="url(#gs-rough)" fillOpacity={0.85} stroke="#1f5a36" strokeOpacity={0.55} strokeWidth={0.8} filter="url(#gs-feather)" />;
  }
  return <ellipse cx={center.x} cy={center.y} rx={26} ry={16} fill="url(#gs-rough)" fillOpacity={0.85} stroke="#1f5a36" strokeOpacity={0.55} />;
}

function OutOfBoundsFeature({ points, center }: { points: { x: number; y: number }[] | null; center: { x: number; y: number } }) {
  if (points) {
    return <path d={ringPath(points)} fill="rgba(255,255,255,0.04)" stroke="#ffffff" strokeOpacity={0.75} strokeWidth={1} strokeDasharray="6 4" />;
  }
  return <ellipse cx={center.x} cy={center.y} rx={28} ry={18} fill="rgba(255,255,255,0.04)" stroke="#ffffff" strokeOpacity={0.7} strokeDasharray="6 4" />;
}

function WasteFeature({ points, center }: { points: { x: number; y: number }[] | null; center: { x: number; y: number } }) {
  if (points) {
    return (
      <g>
        <path d={ringPath(points)} fill="#9c8454" fillOpacity={0.75} stroke="#d8b974" strokeOpacity={0.55} strokeWidth={0.8} />
        <path d={ringPath(points)} fill="url(#gs-sand-stipple)" opacity={0.4} />
      </g>
    );
  }
  return <ellipse cx={center.x} cy={center.y} rx={24} ry={14} fill="#9c8454" fillOpacity={0.7} stroke="#d8b974" strokeOpacity={0.55} />;
}

function PlayerMarker({
  projection,
  player,
  accuracy,
}: {
  projection: FittedProjection;
  player: LatLng;
  accuracy: number | null;
}) {
  const p = projectLatLngToHoleCanvas(player, projection);
  // Approx accuracy ring: scale = pixels per degree of latitude;
  // 1 deg lat ≈ 111000m, so m→px = scale / 111000.
  const metersToPx = projection.scale / 111000;
  const ringPx =
    accuracy != null && accuracy > 0
      ? Math.max(8, Math.min(80, accuracy * metersToPx))
      : 0;
  return (
    <g>
      {ringPx > 0 && (
        <circle
          cx={p.x}
          cy={p.y}
          r={ringPx}
          fill="#F5C84B"
          fillOpacity={0.08}
          stroke="#F5C84B"
          strokeOpacity={0.4}
          strokeWidth={1}
        />
      )}
      <circle cx={p.x} cy={p.y} r={9} fill="#F5C84B" fillOpacity={0.25} />
      <circle cx={p.x} cy={p.y} r={5} fill="#fff" stroke="#F5C84B" strokeWidth={2} />
    </g>
  );
}

function MeasurementLineLayer({
  projection,
  from,
  to,
  unit,
}: {
  projection: FittedProjection;
  from: LatLng;
  to: LatLng;
  unit: "yards" | "meters";
}) {
  const a = projectLatLngToHoleCanvas(from, projection);
  const b = projectLatLngToHoleCanvas(to, projection);
  const m = calculateMeasurementFromTap(from, to, unit);
  const midX = (a.x + b.x) / 2;
  const midY = (a.y + b.y) / 2;
  return (
    <g>
      <line
        x1={a.x}
        y1={a.y}
        x2={b.x}
        y2={b.y}
        stroke="#F5C84B"
        strokeWidth={2}
        strokeDasharray="6 4"
        opacity={0.95}
      />
      <circle cx={b.x} cy={b.y} r={14} fill="#F5C84B" fillOpacity={0.15} />
      <circle cx={b.x} cy={b.y} r={6} fill="#F5C84B" stroke="#1a1300" strokeWidth={1.5} />
      {m && (
        <g transform={`translate(${midX}, ${midY - 14})`}>
          <rect x={-30} y={-12} width={60} height={20} rx={10} fill="#1a1300" stroke="#F5C84B" strokeWidth={1} />
          <text x={0} y={2} textAnchor="middle" fill="#F5C84B" fontSize="11" fontFamily="ui-serif, Georgia">
            {m.distance}{m.unit}
          </text>
        </g>
      )}
    </g>
  );
}
